import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:pokedex/homePage.dart';

class pokemons{
  final String image, name, description, type1, type2, weakness1, weakness2, weakness3,weakness4;
  final int pokeId, power, speed, evolve, evolveSayisi, health;

  pokemons({
    required this.health,
    required this.evolveSayisi,
    required this.evolve,
    required this.speed,
    required this.power,
    required this.weakness1,
    required this.weakness2,
    required this.weakness3,
    required this.weakness4,
    required this.type2,
    required this.type1,
    required this.image,
    required this.name,
    required this.description,
    required this.pokeId,
});

  static String getpokeId(int pokeNumber){
    return pokemonlar[pokeNumber].pokeId.toString();
  }

  static String getpokeName(int pokeNumber){
    return pokemonlar[pokeNumber].name;
  }

  static String getpokeType1(int pokeNumber){
    return pokemonlar[pokeNumber].type1;
  }

  static String getpokeType2(int pokeNumber){
    return pokemonlar[pokeNumber].type2;
  }

  static String getpokeWeakness1(int pokeNumber){
    return pokemonlar[pokeNumber].weakness1;
  }

  static String getpokeWeakness2(int pokeNumber){
    return pokemonlar[pokeNumber].weakness2;
  }

  static String getpokeWeakness3(int pokeNumber){
    return pokemonlar[pokeNumber].weakness3;
  }

  static String getpokeWeakness4(int pokeNumber){
    return pokemonlar[pokeNumber].weakness4;
  }

  static String getpokeDescription(int pokeNumber){
    return pokemonlar[pokeNumber].description;
  }

}


List<pokemons> pokemonlar = [
  pokemons(image: 'assets/mos/001.png', name: 'Florass', description: 'florass', pokeId: 1, type1: 'assets/symbols/grassSymbol.png', type2: 'assets/symbols/poisonSymbol.png', weakness1: 'assets/symbols/fireSymbol.png', weakness2: 'assets/symbols/flyingSymbol.png', weakness3: 'assets/symbols/iceSymbol.png', weakness4: 'yok', power: 5, speed: 4, evolve: 1, evolveSayisi: 1, health: 4),
  pokemons(image: 'assets/mos/002.png', name: 'Sparkie', description: 'sparkie', pokeId: 2, type1: 'assets/symbols/fireSymbol.png', type2: 'yok', weakness1: 'assets/symbols/iceSymbol.png', weakness2: 'assets/symbols/waterSymbol.png', weakness3: 'assets/symbols/flyingSymbol.png', weakness4: 'assets/symbols/rockSymbol.png', power: 5, speed: 4, evolve: 1, evolveSayisi: 2, health: 3),
  pokemons(image: 'assets/mos/003.png', name: 'Sparken', description: 'sparken', pokeId: 3, type1: 'assets/symbols/fireSymbol.png', type2: 'yok', weakness1: 'assets/symbols/iceSymbol.png', weakness2: 'assets/symbols/waterSymbol.png', weakness3: 'assets/symbols/flyingSymbol.png', weakness4: 'assets/symbols/rockSymbol.png', power: 7, speed: 6, evolve: 2, evolveSayisi: 2, health: 5),
  pokemons(image: 'assets/mos/004.png', name: 'Aquadra', description: 'aquadra', pokeId: 4, type1: 'assets/symbols/waterSymbol.png', type2: 'assets/symbols/iceSymbol.png', weakness1: 'assets/symbols/electricSymbol.png', weakness2: 'assets/symbols/grassSymbol.png', weakness3: 'yok', weakness4: 'yok', power: 5, speed: 4, evolve: 1, evolveSayisi: 1, health: 3),
  pokemons(image: 'assets/mos/005.png', name: 'Shockwing', description: 'shockwing', pokeId: 5, type1: 'assets/symbols/flyingSymbol.png', type2: 'assets/symbols/electricSymbol.png', weakness1: 'assets/symbols/rockSymbol.png', weakness2: 'assets/symbols/iceSymbol.png', weakness3: 'assets/symbols/dragonSymbol.png', weakness4: 'yok', power: 5, speed: 5, evolve: 1, evolveSayisi: 2, health: 4),
  pokemons(image: 'assets/mos/006.png', name: 'Zapwing', description: 'zapwing', pokeId: 6, type1: 'assets/symbols/flyingSymbol.png', type2: 'assets/symbols/electricSymbol.png', weakness1: 'assets/symbols/rockSymbol.png', weakness2: 'assets/symbols/iceSymbol.png', weakness3: 'assets/symbols/dragonSymbol.png', weakness4: 'yok', power: 6, speed: 6, evolve: 2, evolveSayisi: 2, health: 5),
  pokemons(image: 'assets/mos/007.png', name: 'Joltur', description: 'joltur', pokeId: 7, type1: 'assets/symbols/electricSymbol.png', type2: 'yok', weakness1: 'assets/symbols/rockSymbol.png', weakness2: 'assets/symbols/grassSymbol.png', weakness3: 'yok', weakness4: 'yok', power: 3, speed: 5, evolve: 1, evolveSayisi: 2, health: 4),
  pokemons(image: 'assets/mos/008.png', name: 'Joltrik', description: 'joltrik', pokeId: 8, type1: 'assets/symbols/electricSymbol.png', type2: 'yok', weakness1: 'assets/symbols/rockSymbol.png', weakness2: 'assets/symbols/grassSymbol.png', weakness3: 'yok', weakness4: 'yok', power: 4, speed: 6, evolve: 2, evolveSayisi: 2, health: 5),
  pokemons(image: 'assets/mos/009.png', name: 'Mysticon', description: 'mysticon', pokeId: 9, type1: 'assets/symbols/psychicSymbol.png', type2: 'yok', weakness1: 'assets/symbols/dragonSymbol.png', weakness2: 'assets/symbols/ghostSymbol.png', weakness3: 'yok', weakness4: 'yok', power: 5, speed: 6, evolve: 1, evolveSayisi: 1, health: 5),
  pokemons(image: 'assets/mos/010.png', name: 'Psypup', description: 'psypup', pokeId: 10, type1: 'assets/symbols/grassSymbol.png', type2: 'assets/symbols/iceSymbol.png', weakness1: 'assets/symbols/fireSymbol.png', weakness2: 'assets/symbols/rockSymbol.png', weakness3: 'assets/symbols/psychicSymbol.png', weakness4: 'yok', power: 3, speed: 5, evolve: 1, evolveSayisi: 2, health: 3),
  pokemons(image: 'assets/mos/011.png', name: 'Psydog', description: 'psydog', pokeId: 11, type1: 'assets/symbols/grassSymbol.png', type2: 'assets/symbols/iceSymbol.png', weakness1: 'assets/symbols/fireSymbol.png', weakness2: 'assets/symbols/rockSymbol.png', weakness3: 'assets/symbols/psychicSymbol.png', weakness4: 'yok', power: 5, speed: 7, evolve: 2, evolveSayisi: 2, health: 6),
  pokemons(image: 'assets/mos/012.png', name: 'Dolphineon', description: 'dolphineon', pokeId: 12, type1: 'assets/symbols/waterSymbol.png', type2: 'assets/symbols/psychicSymbol.png', weakness1: 'assets/symbols/electricSymbol.png', weakness2: 'assets/symbols/iceSymbol.png', weakness3: 'yok', weakness4: 'yok', power: 4, speed: 6, evolve: 1, evolveSayisi: 1, health: 6),
  pokemons(image: 'assets/mos/013.png', name: 'Rockslide', description: 'rockslide', pokeId: 13, type1: 'assets/symbols/rockSymbol.png', type2: 'yok', weakness1: 'assets/symbols/waterSymbol.png', weakness2: 'assets/symbols/flyingSymbol.png', weakness3: 'yok', weakness4: 'yok', power: 3, speed: 5, evolve: 1, evolveSayisi: 2, health: 6),
  pokemons(image: 'assets/mos/014.png', name: 'Rockfist', description: 'rockfist', pokeId: 14, type1: 'assets/symbols/rockSymbol.png', type2: 'yok', weakness1: 'assets/symbols/waterSymbol.png', weakness2: 'assets/symbols/flyingSymbol.png', weakness3: 'yok', weakness4: 'yok', power: 5, speed: 8, evolve: 2, evolveSayisi: 2, health: 6),
  pokemons(image: 'assets/mos/015.png', name: 'Silentpaw', description: 'silentpaw', pokeId: 15, type1: 'assets/symbols/fightingSymbol.png', type2: 'yok', weakness1: 'assets/symbols/ghostSymbol.png', weakness2: 'assets/symbols/psychicSymbol.png', weakness3: 'assets/symbols/iceSymbol.png', weakness4: 'yok', power: 5, speed: 6, evolve: 1, evolveSayisi: 2, health: 5),
  pokemons(image: 'assets/mos/016.png', name: 'Shadowclaw', description: 'shadowclaw', pokeId: 16, type1: 'assets/symbols/fightingSymbol.png', type2: 'yok', weakness1: 'assets/symbols/ghostSymbol.png', weakness2: 'assets/symbols/psychicSymbol.png', weakness3: 'assets/symbols/iceSymbol.png', weakness4: 'yok', power: 6, speed: 7, evolve: 2, evolveSayisi: 2, health: 6),
  pokemons(image: 'assets/mos/017.png', name: 'Electromon', description: 'electromon', pokeId: 17, type1: 'assets/symbols/electricSymbol.png', type2: 'assets/symbols/fightingSymbol.png', weakness1: 'assets/symbols/rockSymbol.png', weakness2: 'assets/symbols/grassSymbol.png', weakness3: 'assets/symbols/ghostSymbol.png', weakness4: 'assets/symbols/psychicSymbol.png', power: 5, speed: 5, evolve: 1, evolveSayisi: 1, health: 4),
  pokemons(image: 'assets/mos/018.png', name: 'Eaglestorm', description: 'eaglestorm', pokeId: 18, type1: 'assets/symbols/flyingSymbol.png', type2: 'yok', weakness1: 'assets/symbols/electricSymbol.png', weakness2: 'assets/symbols/dragonSymbol.png', weakness3: 'yok', weakness4: 'yok', power: 5, speed: 5, evolve: 1, evolveSayisi: 2, health: 5),
  pokemons(image: 'assets/mos/019.png', name: 'Skywing', description: 'skywing', pokeId: 19, type1: 'assets/symbols/flyingSymbol.png', type2: 'yok', weakness1: 'assets/symbols/electricSymbol.png', weakness2: 'assets/symbols/dragonSymbol.png', weakness3: 'yok', weakness4: 'yok', power: 7, speed: 6, evolve: 2, evolveSayisi: 2, health: 7),
  pokemons(image: 'assets/mos/020.png', name: 'Woolie', description: 'woolie', pokeId: 20, type1: 'assets/symbols/electricSymbol.png', type2: 'yok', weakness1: 'assets/symbols/rockSymbol.png', weakness2: 'assets/symbols/ghostSymbol.png', weakness3: 'yok', weakness4: 'yok', power: 2, speed: 3, evolve: 1, evolveSayisi: 3, health: 4),
  pokemons(image: 'assets/mos/021.png', name: 'Wooliec', description: 'wooliec', pokeId: 21, type1: 'assets/symbols/electricSymbol.png', type2: 'yok', weakness1: 'assets/symbols/rockSymbol.png', weakness2: 'assets/symbols/ghostSymbol.png', weakness3: 'yok', weakness4: 'yok', power: 4, speed: 4, evolve: 2, evolveSayisi: 3, health: 5),
  pokemons(image: 'assets/mos/022.png', name: 'Wooliectra', description: 'wooliectra', pokeId: 22, type1: 'assets/symbols/electricSymbol.png', type2: 'yok', weakness1: 'assets/symbols/rockSymbol.png', weakness2: 'assets/symbols/ghostSymbol.png', weakness3: 'yok', weakness4: 'yok', power: 7, speed: 7, evolve: 3, evolveSayisi: 3, health: 6),
  pokemons(image: 'assets/mos/023.png', name: 'Spookums', description: 'spookums', pokeId: 23, type1: 'assets/symbols/ghostSymbol.png', type2: 'yok', weakness1: 'assets/symbols/psychicSymbol.png', weakness2: 'assets/symbols/dragonSymbol.png', weakness3: 'yok', weakness4: 'yok', power: 5, speed: 5, evolve: 1, evolveSayisi: 2, health: 5),
  pokemons(image: 'assets/mos/024.png', name: 'Spookram', description: 'spookram', pokeId: 24, type1: 'assets/symbols/ghostSymbol.png', type2: 'yok', weakness1: 'assets/symbols/psychicSymbol.png', weakness2: 'assets/symbols/dragonSymbol.png', weakness3: 'yok', weakness4: 'yok', power: 7, speed: 7, evolve: 2, evolveSayisi: 2, health: 7),
  pokemons(image: 'assets/mos/025.png', name: 'Nimowl', description: 'nimowl', pokeId: 25, type1: 'assets/symbols/fightingSymbol.png', type2: 'assets/symbols/flyingSymbol.png', weakness1: 'assets/symbols/ghostSymbol.png', weakness2: 'assets/symbols/psychicSymbol.png', weakness3: 'assets/symbols/waterSymbol.png', weakness4: 'yok', power: 5, speed: 4, evolve: 1, evolveSayisi: 2, health: 5),
  pokemons(image: 'assets/mos/026.png', name: 'Wisowl', description: 'wisowl', pokeId: 26, type1: 'assets/symbols/fightingSymbol.png', type2: 'assets/symbols/flyingSymbol.png', weakness1: 'assets/symbols/ghostSymbol.png', weakness2: 'assets/symbols/psychicSymbol.png', weakness3: 'assets/symbols/waterSymbol.png', weakness4: 'yok', power: 7, speed: 6, evolve: 2, evolveSayisi: 2, health: 6),
  pokemons(image: 'assets/mos/027.png', name: 'Fliefox', description: 'fliefox', pokeId: 27, type1: 'assets/symbols/normalSymbol.png', type2: 'yok', weakness1: 'assets/symbols/fightingSymbol.png', weakness2: 'assets/symbols/flyingSymbol.png', weakness3: 'yok', weakness4: 'yok', power: 3, speed: 4, evolve: 1, evolveSayisi: 2, health: 5),
  pokemons(image: 'assets/mos/028.png', name: 'Fluffox', description: 'fluffox', pokeId: 28, type1: 'assets/symbols/normalSymbol.png', type2: 'yok', weakness1: 'assets/symbols/fightingSymbol.png', weakness2: 'assets/symbols/flyingSymbol.png', weakness3: 'yok', weakness4: 'yok', power: 4, speed: 5, evolve: 2, evolveSayisi: 2, health: 6),
  pokemons(image: 'assets/mos/029.png', name: 'Drogie', description: 'drogie', pokeId: 29, type1: 'assets/symbols/iceSymbol.png', type2: 'assets/symbols/dragonSymbol.png', weakness1: 'assets/symbols/fireSymbol.png', weakness2: 'assets/symbols/psychicSymbol.png', weakness3: 'yok', weakness4: 'yok', power: 5, speed: 5, evolve: 1, evolveSayisi: 3, health: 5),
  pokemons(image: 'assets/mos/030.png', name: 'Drogice', description: 'drogice', pokeId: 30, type1: 'assets/symbols/iceSymbol.png', type2: 'assets/symbols/dragonSymbol.png', weakness1: 'assets/symbols/fireSymbol.png', weakness2: 'assets/symbols/psychicSymbol.png', weakness3: 'yok', weakness4: 'yok', power: 6, speed: 7, evolve: 2, evolveSayisi: 3, health: 7),
  pokemons(image: 'assets/mos/031.png', name: 'Drogrost', description: 'drogrost', pokeId: 31, type1: 'assets/symbols/iceSymbol.png', type2: 'assets/symbols/dragonSymbol.png', weakness1: 'assets/symbols/fireSymbol.png', weakness2: 'assets/symbols/psychicSymbol.png', weakness3: 'yok', weakness4: 'yok', power: 8, speed: 9, evolve: 3, evolveSayisi: 3, health: 8),
  pokemons(image: 'assets/mos/032.png', name: 'Monrass', description: 'monrass', pokeId: 32, type1: 'assets/symbols/grassSymbol.png', type2: 'assets/symbols/fightingSymbol.png', weakness1: 'assets/symbols/fireSymbol.png', weakness2: 'assets/symbols/iceSymbol.png', weakness3: 'assets/symbols/ghostSymbol.png', weakness4: 'yok', power: 4, speed: 5, evolve: 1, evolveSayisi: 2, health: 5),
  pokemons(image: 'assets/mos/033.png', name: 'Gorrass', description: 'gorrass', pokeId: 33, type1: 'assets/symbols/grassSymbol.png', type2: 'assets/symbols/fightingSymbol.png', weakness1: 'assets/symbols/fireSymbol.png', weakness2: 'assets/symbols/iceSymbol.png', weakness3: 'assets/symbols/ghostSymbol.png', weakness4: 'yok', power: 6, speed: 6, evolve: 2, evolveSayisi: 2, health: 7),
  pokemons(image: 'assets/mos/034.png', name: 'Flamerock', description: 'flamerock', pokeId: 34, type1: 'assets/symbols/fireSymbol.png', type2: 'yok', weakness1: 'assets/symbols/waterSymbol.png', weakness2: 'assets/symbols/rockSymbol.png', weakness3: 'assets/symbols/iceSymbol.png', weakness4: 'yok', power: 5, speed: 6, evolve: 1, evolveSayisi: 2, health: 5),
  pokemons(image: 'assets/mos/035.png', name: 'Flameburst', description: 'flameburst', pokeId: 35, type1: 'assets/symbols/fireSymbol.png', type2: 'yok', weakness1: 'assets/symbols/waterSymbol.png', weakness2: 'assets/symbols/rockSymbol.png', weakness3: 'assets/symbols/iceSymbol.png', weakness4: 'yok', power: 7, speed: 6, evolve: 2, evolveSayisi: 2, health: 8),
  pokemons(image: 'assets/mos/036.png', name: 'Vaseblade', description: 'vaseblade', pokeId: 36, type1: 'assets/symbols/grassSymbol.png', type2: 'yok', weakness1: 'assets/symbols/fireSymbol.png', weakness2: 'assets/symbols/flyingSymbol.png', weakness3: 'assets/symbols/fightingSymbol.png', weakness4: 'yok', power: 2, speed: 3, evolve: 1, evolveSayisi: 3, health: 5),
  pokemons(image: 'assets/mos/037.png', name: 'Leafblade', description: 'leafblade', pokeId: 37, type1: 'assets/symbols/grassSymbol.png', type2: 'yok', weakness1: 'assets/symbols/fireSymbol.png', weakness2: 'assets/symbols/flyingSymbol.png', weakness3: 'assets/symbols/fightingSymbol.png', weakness4: 'yok', power: 4, speed: 6, evolve: 2, evolveSayisi: 3, health: 6),
  pokemons(image: 'assets/mos/038.png', name: 'Forestblade', description: 'forestblade', pokeId: 38, type1: 'assets/symbols/grassSymbol.png', type2: 'yok', weakness1: 'assets/symbols/fireSymbol.png', weakness2: 'assets/symbols/flyingSymbol.png', weakness3: 'assets/symbols/fightingSymbol.png', weakness4: 'yok', power: 6, speed: 7, evolve: 3, evolveSayisi: 3, health: 7),
  pokemons(image: 'assets/mos/039.png', name: 'Glimmer', description: 'glimmer', pokeId: 39, type1: 'assets/symbols/iceSymbol.png', type2: 'assets/symbols/fightingSymbol.png', weakness1: 'assets/symbols/fireSymbol.png', weakness2: 'assets/symbols/electricSymbol.png', weakness3: 'assets/symbols/dragonSymbol.png', weakness4: 'yok', power: 3, speed: 5, evolve: 1, evolveSayisi: 2, health: 6),
  pokemons(image: 'assets/mos/040.png', name: 'Schimmer', description: 'schimmer', pokeId: 40, type1: 'assets/symbols/iceSymbol.png', type2: 'assets/symbols/fightingSymbol.png', weakness1: 'assets/symbols/fireSymbol.png', weakness2: 'assets/symbols/electricSymbol.png', weakness3: 'assets/symbols/dragonSymbol.png', weakness4: 'yok', power: 5, speed: 7, evolve: 2, evolveSayisi: 2, health: 7),
  pokemons(image: 'assets/mos/041.png', name: 'Dunebelle', description: 'dunebelle', pokeId: 41, type1: 'assets/symbols/rockSymbol.png', type2: 'assets/symbols/flyingSymbol.png', weakness1: 'assets/symbols/waterSymbol.png', weakness2: 'assets/symbols/iceSymbol.png', weakness3: 'assets/symbols/dragonSymbol.png', weakness4: 'yok', power: 5, speed: 5, evolve: 1, evolveSayisi: 1, health: 5),
  pokemons(image: 'assets/mos/042.png', name: 'Infernus', description: 'infernus', pokeId: 42, type1: 'assets/symbols/fireSymbol.png', type2: 'assets/symbols/flyingSymbol.png', weakness1: 'assets/symbols/waterSymbol.png', weakness2: 'assets/symbols/iceSymbol.png', weakness3: 'assets/symbols/dragonSymbol.png', weakness4: 'yok', power: 5, speed: 7, evolve: 1, evolveSayisi: 2, health: 4),
  pokemons(image: 'assets/mos/043.png', name: 'Blazenus', description: 'blazenus', pokeId: 43, type1: 'assets/symbols/fireSymbol.png', type2: 'assets/symbols/flyingSymbol.png', weakness1: 'assets/symbols/waterSymbol.png', weakness2: 'assets/symbols/iceSymbol.png', weakness3: 'assets/symbols/dragonSymbol.png', weakness4: 'yok', power: 6, speed: 8, evolve: 2, evolveSayisi: 2, health: 6),
  pokemons(image: 'assets/mos/044.png', name: 'Whispurr', description: 'whispurr', pokeId: 44, type1: 'assets/symbols/ghostSymbol.png', type2: 'yok', weakness1: 'assets/symbols/psychicSymbol.png', weakness2: 'assets/symbols/dragonSymbol.png', weakness3: 'assets/symbols/waterSymbol.png', weakness4: 'yok', power: 4, speed: 5, evolve: 1, evolveSayisi: 2, health: 4),
  pokemons(image: 'assets/mos/045.png', name: 'Ghosteroid', description: 'ghosteroid', pokeId: 45, type1: 'assets/symbols/ghostSymbol.png', type2: 'yok', weakness1: 'assets/symbols/psychicSymbol.png', weakness2: 'assets/symbols/dragonSymbol.png', weakness3: 'assets/symbols/waterSymbol.png', weakness4: 'yok', power: 6, speed: 7, evolve: 2, evolveSayisi: 2, health: 6),
  pokemons(image: 'assets/mos/046.png', name: 'Toxibug', description: 'toxibug', pokeId: 46, type1: 'assets/symbols/bugSymbol.png', type2: 'assets/symbols/grassSymbol.png', weakness1: 'assets/symbols/fireSymbol.png', weakness2: 'assets/symbols/flyingSymbol.png', weakness3: 'assets/symbols/poisonSymbol.png', weakness4: 'assets/symbols/rockSymbol.png', power: 4, speed: 6, evolve: 1, evolveSayisi: 2, health: 5),
  pokemons(image: 'assets/mos/047.png', name: 'Toxiban', description: 'toxiban', pokeId: 47, type1: 'assets/symbols/bugSymbol.png', type2: 'assets/symbols/grassSymbol.png', weakness1: 'assets/symbols/fireSymbol.png', weakness2: 'assets/symbols/flyingSymbol.png', weakness3: 'assets/symbols/poisonSymbol.png', weakness4: 'assets/symbols/rockSymbol.png', power: 6, speed: 7, evolve: 2, evolveSayisi: 2, health: 7),
  pokemons(image: 'assets/mos/048.png', name: 'Citrusclaw', description: 'citrusclaw', pokeId: 48, type1: 'assets/symbols/normalSymbol.png', type2: 'yok', weakness1: 'assets/symbols/flyingSymbol.png', weakness2: 'assets/symbols/iceSymbol.png', weakness3: 'assets/symbols/fireSymbol.png', weakness4: 'yok', power: 4, speed: 5, evolve: 1, evolveSayisi: 2, health: 6),
  pokemons(image: 'assets/mos/049.png', name: 'Gingerpaw', description: 'gingerpaw', pokeId: 49, type1: 'assets/symbols/normalSymbol.png', type2: 'yok', weakness1: 'assets/symbols/flyingSymbol.png', weakness2: 'assets/symbols/iceSymbol.png', weakness3: 'assets/symbols/fireSymbol.png', weakness4: 'assets/symbols/fireSymbol.png', power: 6, speed: 7, evolve: 2, evolveSayisi: 2, health: 8),
  pokemons(image: 'assets/mos/050.png', name: 'Poliba', description: 'poliba', pokeId: 50, type1: 'assets/symbols/poisonSymbol.png', type2: 'yok', weakness1: 'assets/symbols/fireSymbol.png', weakness2: 'assets/symbols/ghostSymbol.png', weakness3: 'assets/symbols/psychicSymbol.png', weakness4: 'yok', power: 6, speed: 5, evolve: 1, evolveSayisi: 1, health: 6),
  pokemons(image: 'assets/mos/051.png', name: 'Skov', description: 'skov', pokeId: 51, type1: 'assets/symbols/grassSymbol.png', type2: 'yok', weakness1: 'assets/symbols/fireSymbol.png', weakness2: 'assets/symbols/flyingSymbol.png', weakness3: 'assets/symbols/iceSymbol.png', weakness4: 'yok', power: 3, speed: 5, evolve: 1, evolveSayisi: 2, health: 6),
  pokemons(image: 'assets/mos/052.png', name: 'Skovie', description: 'skovie', pokeId: 52, type1: 'assets/symbols/grassSymbol.png', type2: 'yok', weakness1: 'assets/symbols/fireSymbol.png', weakness2: 'assets/symbols/flyingSymbol.png', weakness3: 'assets/symbols/iceSymbol.png', weakness4: 'yok', power: 5, speed: 7, evolve: 2, evolveSayisi: 2, health: 7),
  pokemons(image: 'assets/mos/053.png', name: 'Rhinohorn', description: 'rhinohorn', pokeId: 53, type1: 'assets/symbols/rockSymbol.png', type2: 'assets/symbols/fightingSymbol.png', weakness1: 'assets/symbols/waterSymbol.png', weakness2: 'assets/symbols/iceSymbol.png', weakness3: 'assets/symbols/dragonSymbol.png', weakness4: 'yok', power: 5, speed: 2, evolve: 1, evolveSayisi:2,health:7),
  pokemons(image: 'assets/mos/054.png', name: 'Rhinorock', description: 'rhinorock', pokeId: 54, type1: 'assets/symbols/rockSymbol.png', type2: 'assets/symbols/fightingSymbol.png', weakness1: 'assets/symbols/waterSymbol.png', weakness2: 'assets/symbols/iceSymbol.png', weakness3: 'assets/symbols/dragonSymbol.png', weakness4: 'yok', power: 7, speed: 4, evolve: 2, evolveSayisi:2,health:8),
  pokemons(image: 'assets/mos/055.png', name: 'Seebreeze', description: 'seebreeze', pokeId: 55, type1: 'assets/symbols/waterSymbol.png', type2: 'assets/symbols/iceSymbol.png', weakness1: 'assets/symbols/fireSymbol.png', weakness2: 'assets/symbols/electricSymbol.png', weakness3: 'assets/symbols/flyingSymbol.png', weakness4: 'yok', power: 3, speed: 5, evolve: 1, evolveSayisi:2,health:5),
  pokemons(image: 'assets/mos/056.png', name: 'Seastorm', description: 'seastorm', pokeId: 56, type1: 'assets/symbols/waterSymbol.png', type2: 'assets/symbols/iceSymbol.png', weakness1: 'assets/symbols/fireSymbol.png', weakness2: 'assets/symbols/electricSymbol.png', weakness3: 'assets/symbols/flyingSymbol.png', weakness4: 'yok', power: 5, speed: 7, evolve: 2, evolveSayisi:2,health:8),
  pokemons(image: 'assets/mos/057.png', name: 'Flamie', description: 'flamie', pokeId: 57, type1: 'assets/symbols/fireSymbol.png', type2: 'assets/symbols/flyingSymbol.png', weakness1: 'assets/symbols/waterSymbol.png', weakness2: 'assets/symbols/iceSymbol.png', weakness3: 'assets/symbols/dragonSymbol.png', weakness4: 'yok', power: 5, speed: 4, evolve: 1, evolveSayisi:2,health:6),
  pokemons(image: 'assets/mos/058.png', name: 'Flabie', description: 'flabie', pokeId: 58, type1: 'assets/symbols/fireSymbol.png', type2: 'assets/symbols/flyingSymbol.png', weakness1: 'assets/symbols/waterSymbol.png', weakness2: 'assets/symbols/iceSymbol.png', weakness3: 'assets/symbols/dragonSymbol.png', weakness4: 'yok', power: 7, speed: 6, evolve: 2, evolveSayisi:2,health:8),
  pokemons(image: 'assets/mos/059.png', name: 'Feliphys', description: 'feliphys', pokeId: 59, type1: 'assets/symbols/psychicSymbol.png', type2: 'assets/symbols/fightingSymbol.png', weakness1: 'assets/symbols/ghostSymbol.png', weakness2: 'assets/symbols/rockSymbol.png', weakness3: 'assets/symbols/poisonSymbol.png', weakness4: 'yok', power: 4, speed: 5, evolve: 1, evolveSayisi:2,health:3),
  pokemons(image: 'assets/mos/060.png', name: 'Mindlion', description: 'mindlion', pokeId: 60, type1: 'assets/symbols/psychicSymbol.png', type2: 'assets/symbols/fightingSymbol.png', weakness1: 'assets/symbols/ghostSymbol.png', weakness2: 'assets/symbols/rockSymbol.png', weakness3: 'assets/symbols/poisonSymbol.png', weakness4: 'yok', power: 7, speed: 6, evolve: 2, evolveSayisi:2,health:7),
  pokemons(image: 'assets/mos/061.png', name: 'Dracotide', description: 'dracotide', pokeId: 61, type1: 'assets/symbols/dragonSymbol.png', type2: 'assets/symbols/waterSymbol.png', weakness1: 'assets/symbols/psychicSymbol.png', weakness2: 'assets/symbols/iceSymbol.png', weakness3: 'yok', weakness4: 'yok', power: 6, speed: 5, evolve: 1, evolveSayisi:2,health:5),
  pokemons(image: 'assets/mos/062.png', name: 'Dracoflow', description: 'dracoflow', pokeId: 62, type1: 'assets/symbols/dragonSymbol.png', type2: 'assets/symbols/waterSymbol.png', weakness1: 'assets/symbols/psychicSymbol.png', weakness2: 'assets/symbols/iceSymbol.png', weakness3: 'yok', weakness4: 'yok', power: 8, speed: 7, evolve: 2, evolveSayisi:2,health:7),
  pokemons(image: 'assets/mos/063.png', name: 'Frostbite', description: 'frostbite', pokeId: 63, type1: 'assets/symbols/iceSymbol.png', type2: 'assets/symbols/flyingSymbol.png', weakness1: 'assets/symbols/fireSymbol.png', weakness2: 'assets/symbols/rockSymbol.png', weakness3: 'assets/symbols/dragonSymbol.png', weakness4: 'yok', power: 4, speed: 4, evolve: 1, evolveSayisi:2,health:5),
  pokemons(image: 'assets/mos/064.png', name: 'Frostitoes', description: 'frostitoes', pokeId: 64, type1: 'assets/symbols/iceSymbol.png', type2: 'assets/symbols/flyingSymbol.png', weakness1: 'assets/symbols/fireSymbol.png', weakness2: 'assets/symbols/rockSymbol.png', weakness3: 'assets/symbols/dragonSymbol.png', weakness4: 'yok', power: 5, speed: 6, evolve: 2, evolveSayisi:2,health:6),
  pokemons(image: 'assets/mos/065.png', name: 'Minei', description: 'minei', pokeId: 65, type1: 'assets/symbols/rockSymbol.png', type2: 'yok', weakness1: 'assets/symbols/waterSymbol.png', weakness2: 'assets/symbols/flyingSymbol.png', weakness3: 'yok', weakness4: 'yok', power: 3, speed: 5, evolve: 1, evolveSayisi:2,health:6),
  pokemons(image: 'assets/mos/066.png', name: 'Minerax', description: 'minerax', pokeId: 66, type1: 'assets/symbols/rockSymbol.png', type2: 'yok', weakness1: 'assets/symbols/waterSymbol.png', weakness2: 'assets/symbols/flyingSymbol.png', weakness3: 'yok', weakness4: 'yok', power: 5, speed: 6, evolve: 2, evolveSayisi:2,health:7),
  pokemons(image: 'assets/mos/067.png', name: 'Fluffernut', description: 'fluffernut', pokeId: 67, type1: 'assets/symbols/grassSymbol.png', type2: 'assets/symbols/psychicSymbol.png', weakness1: 'assets/symbols/fireSymbol.png', weakness2: 'assets/symbols/ghostSymbol.png', weakness3: 'assets/symbols/iceSymbol.png', weakness4: 'yok', power: 4, speed: 5, evolve: 1, evolveSayisi:2,health:5),
  pokemons(image: 'assets/mos/068.png', name: 'Razorleaf', description: 'razorleaf', pokeId: 68, type1: 'assets/symbols/grassSymbol.png', type2: 'assets/symbols/psychicSymbol.png', weakness1: 'assets/symbols/fireSymbol.png', weakness2: 'assets/symbols/ghostSymbol.png', weakness3: 'assets/symbols/iceSymbol.png', weakness4: 'yok', power: 6, speed: 7, evolve: 2, evolveSayisi:2,health:7),
  pokemons(image: 'assets/mos/069.png', name: 'Spork', description: 'spork', pokeId: 69, type1: 'assets/symbols/electricSymbol.png', type2: 'yok', weakness1: 'assets/symbols/rockSymbol.png', weakness2: 'assets/symbols/flyingSymbol.png', weakness3: 'assets/symbols/bugSymbol.png', weakness4: 'yok', power: 3, speed: 6, evolve: 1, evolveSayisi:3,health:4),
  pokemons(image: 'assets/mos/070.png', name: 'Sporkle', description: 'sporkle', pokeId: 70, type1: 'assets/symbols/electricSymbol.png', type2: 'yok', weakness1: 'assets/symbols/rockSymbol.png', weakness2: 'assets/symbols/flyingSymbol.png', weakness3: 'assets/symbols/bugSymbol.png', weakness4: 'yok', power: 5, speed: 7, evolve: 2, evolveSayisi:3,health:6),
  pokemons(image: 'assets/mos/071.png', name: 'Zazzle', description: 'zazzle', pokeId: 71, type1: 'assets/symbols/electricSymbol.png', type2: 'yok', weakness1: 'assets/symbols/rockSymbol.png', weakness2: 'assets/symbols/flyingSymbol.png', weakness3: 'assets/symbols/bugSymbol.png', weakness4: 'yok', power: 7, speed: 8, evolve: 3, evolveSayisi:3,health:7),
  pokemons(image: 'assets/mos/072.png', name: 'Chiliwrath', description: 'chiliwrath', pokeId: 72, type1: 'assets/symbols/fireSymbol.png', type2: 'yok', weakness1: 'assets/symbols/waterSymbol.png', weakness2: 'assets/symbols/iceSymbol.png', weakness3: 'assets/symbols/flyingSymbol.png', weakness4: 'yok', power: 6, speed: 5, evolve: 1, evolveSayisi:2,health:5),
  pokemons(image: 'assets/mos/073.png', name: 'Chiliclaw', description: 'chiliclaw', pokeId: 73, type1: 'assets/symbols/fireSymbol.png', type2: 'yok', weakness1: 'assets/symbols/waterSymbol.png', weakness2: 'assets/symbols/iceSymbol.png', weakness3: 'assets/symbols/flyingSymbol.png', weakness4: 'yok', power: 8, speed: 7, evolve: 2, evolveSayisi:2,health:7),
  pokemons(image: 'assets/mos/074.png', name: 'Doldog', description: 'doldog', pokeId: 74, type1: 'assets/symbols/waterSymbol.png', type2: 'assets/symbols/iceSymbol.png', weakness1: 'assets/symbols/electricSymbol.png', weakness2: 'assets/symbols/fireSymbol.png', weakness3: 'assets/symbols/flyingSymbol.png', weakness4: 'yok', power: 6, speed: 6, evolve: 1, evolveSayisi:1,health:6),
  pokemons(image: 'assets/mos/075.png', name: 'Roseburst', description: 'roseburst', pokeId: 75, type1: 'assets/symbols/poisonSymbol.png', type2: 'assets/symbols/grassSymbol.png', weakness1: 'assets/symbols/fireSymbol.png', weakness2: 'assets/symbols/flyingSymbol.png', weakness3: 'assets/symbols/iceSymbol.png', weakness4: 'yok', power: 6, speed: 4, evolve: 1, evolveSayisi:2,health:5),
  pokemons(image: 'assets/mos/076.png', name: 'Flowerburst', description: 'flowerburst', pokeId: 76, type1: 'assets/symbols/poisonSymbol.png', type2: 'assets/symbols/grassSymbol.png', weakness1: 'assets/symbols/fireSymbol.png', weakness2: 'assets/symbols/flyingSymbol.png', weakness3: 'assets/symbols/iceSymbol.png', weakness4: 'yok', power: 8, speed: 7, evolve: 2, evolveSayisi:2,health:6),
  pokemons(image: 'assets/mos/077.png', name: 'Frostie', description: 'frostie', pokeId: 77, type1: 'assets/symbols/iceSymbol.png', type2: 'assets/symbols/fightingSymbol.png', weakness1: 'assets/symbols/fireSymbol.png', weakness2: 'assets/symbols/psychicSymbol.png', weakness3: 'assets/symbols/ghostSymbol.png', weakness4: 'yok', power: 5, speed: 5, evolve: 1, evolveSayisi:2,health:5),
  pokemons(image: 'assets/mos/078.png', name: 'Froster', description: 'froster', pokeId: 78, type1: 'assets/symbols/iceSymbol.png', type2: 'assets/symbols/fightingSymbol.png', weakness1: 'assets/symbols/fireSymbol.png', weakness2: 'assets/symbols/psychicSymbol.png', weakness3: 'assets/symbols/ghostSymbol.png', weakness4: 'yok', power: 8, speed: 7, evolve: 2, evolveSayisi:2,health:7),
  pokemons(image: 'assets/mos/079.png', name: 'Dolie', description: 'dolie', pokeId: 79, type1: 'assets/symbols/waterSymbol.png', type2: 'yok', weakness1: 'assets/symbols/electricSymbol.png', weakness2: 'assets/symbols/flyingSymbol.png', weakness3: 'yok', weakness4: 'yok', power: 5, speed: 4, evolve: 1, evolveSayisi:2,health:4),
  pokemons(image: 'assets/mos/080.png', name: 'Dolphie', description: 'dolphie', pokeId: 80, type1: 'assets/symbols/waterSymbol.png', type2: 'yok', weakness1: 'assets/symbols/electricSymbol.png', weakness2: 'assets/symbols/flyingSymbol.png', weakness3: 'yok', weakness4: 'yok', power: 7, speed: 6, evolve: 2, evolveSayisi:2,health:7),
  pokemons(image: 'assets/mos/081.png', name: 'Fenr', description: 'fenr', pokeId: 81, type1: 'assets/symbols/dragonSymbol.png', type2: 'assets/symbols/poisonSymbol.png', weakness1: 'assets/symbols/fireSymbol.png', weakness2: 'assets/symbols/iceSymbol.png', weakness3: 'assets/symbols/waterSymbol.png', weakness4: 'yok', power: 6, speed: 5, evolve: 1, evolveSayisi:2,health:6),
  pokemons(image: 'assets/mos/082.png', name: 'Fenrago', description: 'fenrago', pokeId: 82, type1: 'assets/symbols/dragonSymbol.png', type2: 'assets/symbols/poisonSymbol.png', weakness1: 'assets/symbols/fireSymbol.png', weakness2: 'assets/symbols/iceSymbol.png', weakness3: 'assets/symbols/waterSymbol.png', weakness4: 'yok', power: 8, speed: 7, evolve: 2, evolveSayisi:2,health:8),
  pokemons(image: 'assets/mos/083.png', name: 'Mindwave', description: 'mindwave', pokeId: 83, type1: 'assets/symbols/ghostSymbol.png', type2: 'assets/symbols/psychicSymbol.png', weakness1: 'assets/symbols/dragonSymbol.png', weakness2: 'assets/symbols/waterSymbol.png', weakness3: 'yok', weakness4: 'yok', power: 6, speed: 4, evolve: 1, evolveSayisi:2,health:5),
  pokemons(image: 'assets/mos/084.png', name: 'Psywave', description: 'psywave', pokeId: 84, type1: 'assets/symbols/ghostSymbol.png', type2: 'assets/symbols/psychicSymbol.png', weakness1: 'assets/symbols/dragonSymbol.png', weakness2: 'assets/symbols/waterSymbol.png', weakness3: 'yok', weakness4: 'yok', power: 8, speed: 6, evolve: 2, evolveSayisi:2,health:7),
  pokemons(image: 'assets/mos/085.png', name: 'Boolder', description: 'boolder', pokeId: 85, type1: 'assets/symbols/rockSymbol.png', type2: 'assets/symbols/bugSymbol.png', weakness1: 'assets/symbols/waterSymbol.png', weakness2: 'assets/symbols/iceSymbol.png', weakness3: 'assets/symbols/flyingSymbol.png', weakness4: 'yok', power: 4, speed: 5, evolve: 1, evolveSayisi:2,health:3),
  pokemons(image: 'assets/mos/086.png', name: 'Boolderback', description: 'boolderback', pokeId: 86, type1: 'assets/symbols/rockSymbol.png', type2: 'assets/symbols/bugSymbol.png', weakness1: 'assets/symbols/waterSymbol.png', weakness2: 'assets/symbols/iceSymbol.png', weakness3: 'assets/symbols/flyingSymbol.png', weakness4: 'yok', power: 6, speed: 7, evolve: 2, evolveSayisi:2,health:5),
  pokemons(image: 'assets/mos/087.png', name: 'Aquazoid', description: 'aquazoid', pokeId: 87, type1: 'assets/symbols/waterSymbol.png', type2: 'yok', weakness1: 'assets/symbols/psychicSymbol.png', weakness2: 'assets/symbols/ghostSymbol.png', weakness3: 'assets/symbols/poisonSymbol.png', weakness4: 'yok', power: 6, speed: 6, evolve: 1, evolveSayisi:1,health:5),
  pokemons(image: 'assets/mos/088.png', name: 'Thunderstrike', description: 'thunderstrike', pokeId: 88, type1: 'assets/symbols/electricSymbol.png', type2: 'assets/symbols/fightingSymbol.png', weakness1: 'assets/symbols/rockSymbol.png', weakness2: 'assets/symbols/fireSymbol.png', weakness3: 'assets/symbols/dragonSymbol.png', weakness4: 'yok', power: 9, speed: 9, evolve: 1, evolveSayisi:1,health:8),
  pokemons(image: 'assets/mos/089.png', name: 'Bippitibop', description: 'bippitibop', pokeId: 89, type1: 'assets/symbols/ghostSymbol.png', type2: 'yok', weakness1: 'assets/symbols/psychicSymbol.png', weakness2: 'assets/symbols/dragonSymbol.png', weakness3: 'yok', weakness4: 'yok', power: 6, speed: 6, evolve: 1, evolveSayisi:1,health:7),
  pokemons(image: 'assets/mos/090.png', name: 'Venomous', description: 'venomous', pokeId: 90, type1: 'assets/symbols/poisonSymbol.png', type2: 'yok', weakness1: 'assets/symbols/rockSymbol.png', weakness2: 'assets/symbols/fireSymbol.png', weakness3: 'assets/symbols/iceSymbol.png', weakness4: 'yok', power: 4, speed: 5, evolve: 1, evolveSayisi:1,health:6),
  pokemons(image: 'assets/mos/091.png', name: 'Psycodactyl', description: 'psycodactyl', pokeId: 91, type1: 'assets/symbols/dragonSymbol.png', type2: 'assets/symbols/psychicSymbol.png', weakness1: 'assets/symbols/ghostSymbol.png', weakness2: 'assets/symbols/iceSymbol.png', weakness3: 'assets/symbols/dragonSymbol.png', weakness4: 'assets/pokeTypes/RockType.png', power: 9, speed: 8, evolve: 1, evolveSayisi:1,health:9),
 ];

