import 'dart:ui';

import 'package:get/get.dart';

class language extends Translations {
  static final varsayilan = Locale("en", "US");
  static final diller=[
    Locale("en","US"),
    Locale("tr","TR"),
    Locale("ar", "AR")
  ];
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'failedbuy': 'Purchase Failed!',
      'easylogin': 'EASY LOGIN',
      'easyregister': 'EASY REGISTER',
      'no': 'No',
      'yes': 'Yes',
      'error': 'ERROR',
      'mail': 'Enter your mail...',
      'validMail': 'Please enter a valid email address...',
      'password': 'Enter your password...',
      'passwordLength': 'Password must be at least 6 characters...',
      'login': 'LOGIN',
      'register': 'REGISTER',
      'profile': 'Profile',
      'mycollection': 'My Collection',
      'signout': 'SIGN OUT',
      'watch2x': 'ADS for 2x',
      'shoppingpage': 'Monster Buy Page',
      'monsterbuy': 'Do you approve the monster purchase?',
      'buy': 'BUY',
      'watch': 'ADS for 1 candy',
      'cancel': 'CANCEL',
      'succesfulbuy': 'PURCHASE SUCCESFULL',
      'unsuccesfulbuy': 'PURCHASE FAILED',
      'okay': 'OKAY',
      'succesful': 'SUCCESFUL',
      'unsuccesful': 'FAILED',
      'selectfighter': 'Select Your Fighter',
      'congratulations': 'Congratulations',
      'solved': 'You have solved the puzzle.',
      'youwon': 'You won!',
      'gameover': 'Game Over',
      'youlost': 'You Lost!',
      'isnotready': 'is not ready for this',
      'verypowerful': 'Very powerful attack from',
      'powerful': 'Powerful attack from',
      'weak': 'Weak attack from',
      'health': 'HEALTH',
      'time': 'Time',
      'second': 'sec',
      'cardgame': 'Card Matching',
      'hold': 'HOLD',
      'repeat': 'Repeat',
      'presswhenyouwon': 'Press when you won',
      'poketype': 'Monster Type',
      'weakness': 'Weaknesses',
      'power': 'Power',
      'speed': 'Speed',
      'evolve': 'Evolve',
      'health2': 'Health',
      'move': 'Move',
      'chooseimage': 'Choose Image',
      'exitgame': 'Exit the game for',
      'start': 'Start',
      'pause': 'Pause',
      'left': 'LEFT',
      'right': 'RIGHT',
      'boost': 'BOOST',
      'rotate': 'ROTATE',
      'resume': 'Resume',
      'pausegame': 'Pause Game',
      'adsfor': 'Ads for',
      'watchAds': 'Watch ADS',
      'next': 'Next',
      'alreadybuyed': 'You already have this Monster',
      'confirmcard': 'When you complete the game, you earn 1 Star. You can continue the game for 1 Energy.',
      'back': 'Back',
      'confirmmine': 'When you complete the game, you earn 5 Star. You can continue the game for 1 Energy.',
      'lookmines': 'Look at the mines',
      'letsgo': "Let's Go",
      'hintenergy': 'Energy is automatically loaded into your account every 5 minutes or you can buy energy from the Shop page.',
      'skate': 'You earn 1 Star for every 20 points in the game. You can continue the game for 2 Energy.',
      'monsterfly': 'You earn 1 Star for every 10 points in the game. You can continue the game for 2 Energy.',
      'monstertetris': 'You earn 1 Star for every 1000 points in the game. You can continue the game for 2 Energy.',
      'puzzlesize': 'Puzzle Size',
      'choosepuzzlesize': 'Choose Puzzle Size',
      'games': 'Games',
      'backtomainmenu': 'Back to main menu',
      'florass': 'Florass is the grass creature in the Monster world. It feeds on leaves and has poisonous spines. It can be used in defense and attack, it benefits its owner.',
      'sparkie': 'There is eternal fire in his body that burns until he dies. He spews hot fire in his attacks. He is a natural leader and a respected hunter.',
      'sparken': 'His most well-known attack is the fire hose. He became very powerful thanks to the fire hose that he spewed from his very powerful jaw.',
      'aquadra': 'Aquadra is a water-type creature in the Monster world that can control the water elements. Its body is optimized for water and it has the ability to swim fast.',
      'shockwing': 'Shockwing is a flying and electric type creature found in the Monster world. It is a powerful creature that can fly at high speed and use electrical charges.',
      'zapwing': 'It provides superiority over its competitors thanks to its high-speed flight ability and ability to use electrical loads.',
      'joltur': 'Joltur is an electric-type creature found in the Monster world. It can control electrical energy and make high-voltage attacks.',
      'joltrik': ' It can more effectively control electrical energy and use electrical charges for defensive purposes as well as high voltage attacks.',
      'mysticon': 'He can attack and defend his enemies using his mental powers. At the same time, he can solve many problems thanks to his intelligence and mental abilities.',
      'psypup': 'Using his mental powers, he can discover the weak spots of his enemies and control the grass elements. In addition, with its cute appearance and playful personality, it can provide fun moments for its owner.',
      'psydog': 'She can use her mental powers more effectively and control the grass elements more thoroughly.',
      'dolphineon': 'He is known for having an intelligent and curious character and has an impressive appearance with his movements in the water.',
      'rockslide': 'He has a strong musculature and a solid body. He can hit the ground with shock waves that shake his opponents and control stone elements. He has a strong and determined personality.',
      'rockfist': 'With his immense strength, he can shake the ground and deal devastating blows to his opponents. He can use the stone elements more effectively and his defense mechanisms are also very developed.',
      'silentpaw': 'He can sneak up on his opponents and attack, and their quick moves make them easy to escape. It has an intelligent and alert character and offers a loyal companionship to its owner.',
      'shadowclaw': 'It can attack its opponents by approaching silently. Thanks to its strong claws and sharp teeth, it can deliver powerful blows and easily defeat its enemies. He has a stubborn and courageous personality.',
      'electromon': "It is an electric type Monster. He can carry an electric charge, dealing damage to his enemies and moving quickly.",
      'eaglestorm': "It is a Flying type Monster. Thanks to its powerful wings, it can fly quickly and attack its enemies from high places.",
      'skywing': "It is a Flying type Monster. It uses its sharp claws in its attacks and can fly at high speeds thanks to its powerful wings.",
      'woolie': "It is an Electric type Monster. Their soft wool carries high voltage electrical charges and attacks their enemies.",
      'wooliec': "It is an evolution of Woolie. It carries a stronger electrical charge and their wool is thicker and more resistant.",
      'wooliectra': "It is an evolution of Wooliec. It carries high-voltage electrical charges and its wool glows like lightning. He is more skilled in defense and attack.",
      'spookums': "It is a Ghost type Monster. It has the form of a ghost that looks cute. He uses different tricks to frighten and annoy his enemies.",
      'spookram': "It is a top evolution of Spookums. It takes on a more powerful ghost form and can scare its enemies more effectively. It also has powerful Ghost-type attacks.",
      'nimowl': "It is a psychic-type Monster and resembles an owl. He's smart and fast, and can take out his enemies with confusing psychic attacks.",
      'wisowl': "It is a higher evolution of the Nimowl. It has sharper vision and is ideal for night hunting. Wisowl has stronger psychic attacks capable of mentally manipulating his enemies.",
      'fliefox': "Fliefox is a fox-like Normal type in the Monster world. It can run very fast and jump. He has a sneaky nature and can launch surprising attacks on his enemies.",
      'fluffox': "Fluffox is an upper evolution of Fliefox in Monster world. It is more cunning and powerful. Its fur also provides protection as it flies through the air, and its sharp claws can injure its opponents.",
      'drogie': 'It is a dragon-like monster with the element of ice. It can fly in the sky and make deadly ice exits.',
      'drogice': 'Transforms into an even stronger ice dragon. He can make stronger ice attacks and move faster.',
      'drogrost': 'It can control water as well as ice. It is much bigger and stronger and gives an overwhelming advantage against other monsters.',
      'monrass': "Monkey-like grass type Monster. It's very good with vines.",
      'gorrass': "It is an evolution of Monrass. Its body, covered with vines and leaves, resembles a gorilla.",
      'flamerock': 'This ant-like fire-type Monster moves very fast. And fire attacks can be very hurtful.',
      'flameburst': "It is an upper evolution of Flamerock. Deals deadly blows to his foe with his firebite attack, along with evolutionary heads.",
      'vaseblade': 'It has the ability to control the grass since the day it grows from seed. But he is still doomed to the flowerpot.',
      'leafblade': "It is a higher evolution of Vaseblade. Now its roots are strong and it is separated from the pot. However, grass-type attacks are faster.",
      'forestblade': "It is an evolution of Leafblade. With this evolution, he unlocks the ability to call into the forest and can use the vines and leaves of the forest.",
      'glimmer': 'It is known as the little fairy of the ice. It can form an ice hose by flapping its wings very fast.',
      'schimmer': "It is an evolution of Glimmer. With this evolution, although his former speed has decreased a bit, his ice attacks have become quite stronger.",
      'dunebelle': 'She is the lone fairy of the desert. It can create sandstorms with flapping wings and evade enemy attacks.',
      'infernus': 'She is a fire type fairy. It has high firepower and is an expert in fire control.',
      'blazenus': "It is a superevolution of Infernus. It has even more powerful fire capabilities and has a larger wingspan, allowing it to fly faster.",
      'whispurr': "It is a 'Ghost' type creature that looks like a cat, moves fast and has ghost powers.",
      'ghosteroid': 'It is an evolution with stronger ghost powers and can become stronger by absorbing the energies of other creatures.',
      'toxibug': "It is the most powerful insect in the Monster universe. It can't fly very fast, but its attacks are quite effective.",
      'toxiban': "It is an evolution of Toxibug. It can fly very fast with its developed wings. You don't want to be around him when he makes that vomit attack.",
      'citrusclaw': "Resembling an orange feral cat, this Monster attacks enemies with quick paws. He is also an expert at dodging enemy attacks.",
      'gingerpaw': "A higher evolution of Citrusclaw. With this evolution, he added speed to his speed and his paw blows became stronger. And now he's an expert at hiding.",
      'poliba': 'When it wants, it explodes the sac on its head and attacks its enemies with its poison. With its regeneration feature, it renews its pouch in a very short time.',
      'skov': 'Thanks to his power to control flowers and leaves, he can attack his enemies or defend himself. It is harmless as long as it is not necessary to protect itself.',
      'skovie': "A higher evolution of Skov. Leaf and flower control ability is very developed. He can even remove a flower from its seed to attack his enemies.",
      'rhinohorn': "It has skin that is tougher than steel. In this way, his defensive ability is highly developed. Despite its weight, it is very fast.",
      'rhinorock': "It is a higher evolution of Rhinohorn. Horn attack damage has been greatly increased with this evolution.",
      'seebreeze': 'It is usually seen in seas or beaches. It is very human. It can move very quickly underwater while hunting.',
      'seastorm': "It is an evolution of Seebreeze. His armor has thickened, but he has also become beautiful. Defeats opponents by creating a water vortex.",
      'flamie': 'Thanks to its wings, it can move quickly through the air and throw fireballs at its enemies.',
      'flabie': 'It has high resistance to fire and is highly resistant to fire-based attacks of its enemies.',
      'feliphys': "It is a Monster that is thought to have lived since ancient times. It is as strong as it looks cute. He can control everything with his psychic powers.",
      'mindlion': "It is a superevolution of Feliphys. He loves to eliminate his enemies by controlling their intelligence. He is a natural leader.",
      'dracotide': 'He is a lovely member of the land of dragons. It can fly very fast and with it also skillfully control the water.',
      'dracoflow': "Although it looks scary due to the size of its body, it is a very cute Monster. He added strength to his power with his tail blows.",
      'frostbite': 'It is very resistant to cold and can use the cold to its advantage. You must escape from his mighty jaw.',
      'frostitoes': "It is an evolution of Frostbite. Its cold resistance has increased even more and its claws have become much stronger. It can fly very high.",
      'minei': "He is a miner and a cute Monster. It can dig up the ground quickly, hide or attack.",
      'minerax': "It is a higher evolution of Minei. He can now dig and move through the ground much faster.",
      'fluffernut': 'Fluffetnut can poison his enemies by creating a field of grass filled with poisonous dust. It also has high resilience to the attacks of its enemies.',
      'razorleaf': 'Thanks to its sharp blade-like leaves, it can easily cut and shred its enemies. Also, the poison powder attack has become much stronger.',
      'spork': "He may be the cutest member of the Monster universe. He cannot yet use his ability to control electricity very well.",
      'sporkle': "It is a higher evolution of Spork. He has now learned to control electricity and with that he has produced several attacks to take down his enemies.",
      'zazzle': "It is an upper evolution of Sporkle. Thanks to its elongated tail, it can steer with electric currents.",
      'chiliwrath': "Being a natural leader, this Monster has increased his strength thanks to his fire control ability.",
      'chiliclaw': "It is very difficult to beat due to stronger claw strikes and hotter fire. It's not wise to fight him",
      'doldog': 'She can run very fast and attack her enemies with her ice control ability.',
      'roseburst': "Thanks to her high-speed moves, she can evade her enemies' attacks and poison them using herb spray from afar.",
      'flowerburst': 'It can camouflage very well in the forest. He sneaks up on his enemy and can poison him if he wants to.',
      'frostie': "He is a very cute looking but dangerous Monster. Can deliver powerful body blows.",
      'froster': "It is an evolution of Frostie. His body blows have improved, and he has also strengthened his strength with his ice control ability.",
      'dolie': 'It can swim very quickly and attack its enemies with water whirlpools.',
      'dolphie': 'He is very human and loves to swim with people. He can take down his enemies with water hammers.',
      'fenr': 'He is a lovely member of the land of dragons. It can fly very fast and make a poison attack.',
      'fenrago': 'Its body has grown considerably and its wings have elongated. Thanks to this, it can fly very fast. The poison in his body has also become stronger. In this way, he can defeat his enemies.',
      'mindwave': "The robot capable of psychic attacks is Monster. He is said to have psychically attacked himself and discovered how to fly.",
      'psywave': 'He specializes in psychic attacks. And his armor is harder than steel. It is not easy to defeat him.',
      'boolder': 'It is very small and very fast. It can dig the soil very well. It can hide under it or attack the enemy with your pickaxe.',
      'boolderback': "It is an evolution of Boolder. He can run very fast. And he is an expert in rock attacks.",
      'aquazoid': 'He can move quickly underwater and defend himself against the attacks of his enemies by using water bubbles. It can survive underwater for a long time.',
      'thunderstrike': "This Monster can release electric current wherever he sets foot. It makes very strong voltage attacks. He is a natural leader.",
      'bippitibop': "He loves to have fun with his enemies. He is a very good magician and also a very powerful Monster",
      'venomous': "It is a very poisonous Monster. It has a high dose of poison in its tail. It can move fast.",
      'psycodactyl': 'Using his brain power, he can read the minds of his enemies and create turmoil in their minds. Also, he can evade the attacks of his enemies thanks to his high-speed flight ability.',
      'contactus': 'CONTACT US',
      'playagain': 'Do you wanna play again?',
      'end': 'End',
      'withdraw': 'Do you want to withdraw for',
      'outofenergy': "You don't have the energy to play the game!",
      'watchadsforenergy': 'Watch Ads for 5 Energy',
      'hintcandy': "You can buy Monsters from the 'My Collection' page with the collected Candies. To earn Candy, you can play mini-games or get them from the Shop.",
      'seeyousoon': 'Coming soon',
      'email1': 'Please use simple email. john@example.com - john@gmail.com - john1@example.com',
      'loginhint': 'If you do not have an account, you can continue by clicking EASY REGISTER. If you have an account, you can continue with EASY LOGIN.',
      '1dollar': '~ 1\$',
      '5dollar': '~ 5\$',
      '10dollar': '~ 10\$',
      'youneedtobuy': 'You must purchase this Monster to enter this page',
    },
    'tr_TR': {
      'youneedtobuy': "Bu sayfaya girebilmek için bu Monster'i satın almalısınız",
      '1dollar': '~ 5TL',
      '5dollar': '~ 25TL',
      '10dollar': '~ 50TL',
      'failedbuy': 'Satın Alma Başarısız!',
      'loginhint': 'Hesabın yoksa KOLAY KAYIT\'a tıklayarak devam edebilirsin. Hesabın varsa KOLAY GİRİŞ\'le devam edebilirsin.',
      'easylogin': 'KOLAY GIRIS',
      'easyregister': 'KOLAY KAYIT',
      'seeyousoon': 'Yakında sizlerle',
      'hintcandy': "Toplanan Candy'lerle 'Koleksiyonum' sayfasından Monster alabilirsin. Candy kazanmak için mini oyun oynayabilir veya Market'ten elde edebilirsin.",
      'hintenergy': 'Energy her 5 dakikada otomatik hesabına yüklenir veya Market sayfasından enerji alabilirsin.',
      'no': 'Hayır',
      'yes': 'Evet',
      'withdraw': 'Çekilmek istiyor musun? =',
      'error': 'HATA',
      'mail': 'Mail giriniz...',
      'validMail': 'Gecerli bir email giriniz...',
      'password': 'Şifrenizi giriniz...',
      'passwordLength': 'Şifreniz en az 6 karakter olmalıdır...',
      'login': 'GIRIS',
      'register': 'KAYIT OL',
      'profile': 'Profil',
      'mycollection': 'Koleksiyonum',
      'email1': 'Lütfen basit bir email kullanın. john@example.com - john@gmail.com - john1@example.com',
      'signout': 'ÇIKIŞ YAP',
      'shoppingpage': 'Canavar Satın Al',
      'monsterbuy': 'Canavar satın alımını onaylıyor musunuz?',
      'buy': 'SATIN AL',
      'cancel': 'VAZGEÇ',
      'watch2x': '2x İçin Reklam',
      'succesfulbuy': 'SATIN ALMA BAŞARILI',
      'unsuccesfulbuy': 'SATIN ALMA BAŞARISIZ',
      'okay': 'TAMAM',
      'succesful': 'BAŞARILI',
      'unsuccesful': 'BAŞARISIZ',
      'selectfighter': 'Kahramanını Seç',
      'congratulations': 'Tebrikler',
      'solved': 'Puzzleyi başarıyla çözdün',
      'youwon': 'Kazandın!',
      'watch': '1 candy için reklam',
      'watchAds': 'Video İzle',
      'gameover': 'Oyun Bitti',
      'youlost': 'Kaybettin!',
      'isnotready': 'buna hazır değil',
      'verypowerful': 'Çok güçlü bir atak yaptı',
      'powerful': 'Güçlü bir atak yaptı',
      'weak': 'Zayıf atak yaptı',
      'health': 'CAN',
      'time': 'Süre',
      'second': 'sn',
      'cardgame': 'Kart Eşleştirme',
      'hold': 'Basılı tut',
      'repeat': 'Yeniden',
      'lookmines': 'Mayınlara bak',
      'presswhenyouwon': 'Kazandığında tıkla',
      'poketype': 'Canavar Tipi',
      'weakness': 'Zayıflıklar',
      'power': 'Güç',
      'speed': 'Hız',
      'evolve': 'Evrim',
      'health2': 'Can',
      'move': 'Hamle',
      'chooseimage': 'Resim Seçin',
      'exitgame': 'Kazandığınız şeker karşılığı oyundan çık: ',
      'alreadybuyed': "Zaten bu Monster'a sahipsin.",
      'start': 'Başla',
      'pause': 'Durdur',
      'left': 'SOL',
      'right': 'SAĞ',
      'boost': 'HIZLANDIR',
      'rotate': 'DÖNDÜR',
      'resume': 'Devam',
      'pausegame': 'Oyun Durdu',
      'adsfor': 'Reklam izle',
      'next': 'Sıradaki',
      'end': 'Bitir',
      'confirmcard': 'Oyunu kazandığında 1 candy kazanırsın. 1 enerji karşılığı oyuna devam edebilirsin.',
      'confirmmine': 'Oyunu kazandığında 5 candy kazanırsın. 1 enerji karşılığı oyuna devam edebilirsin.',
      'back': 'Geri',
      'letsgo': "Başla",
      'skate': 'Her 20 skor karşılığı 1 şeker kazanırsın. 2 enerji karşılığı devam edebilirsin.',
      'monsterfly': 'Her 10 skor karşılığı 1 şeker kazanırsın. 2 enerji karşılığı devam edebilirsin.',
      'monstertetris': 'Her 1000 skor karşılığı 1 şeker kazanırsın. 2 enerji karşılığı devam edebilirsin.',
      'puzzlesize': 'Puzzle Boyutu Seçin',
      'choosepuzzlesize': 'Puzzle Boyutu',
      'games': 'Oyunlar',
      'backtomainmenu': 'Ana menüye dön',
      'florass': 'Florass, Monster dünyasında çimen yaratığıdır. Yapraklarıyla beslenir ve zehirli dikenleri vardır. Savunma ve saldırıda kullanılabilir, sahibine fayda sağlar.',
      'sparkie': 'Vücudunda ölene kadar yanan sonsuz ateş vardır. Saldırılarında sıcak ateş kusar . Doğal  bir lider ve saygın bir avcıdır.',
      'sparken': 'En bilindik saldırısı ateş hortumudur. O çok güçlü çenesinden püskürttüğü ateş hortumu sayesinde çok güçlü bir hale geldi.',
      'aquadra': 'Aquadra, Monster dünyasında su elementlerini kontrol edebilen bir su tipi yaratıktır. Vücudu suya göre optimize edilmiştir ve hızlı yüzme yeteneğine sahiptir.',
      'shockwing': 'Shockwing, Monster dünyasında bulunan bir flying ve electrik tipi yaratıktır. Yüksek hızda uçabilen ve elektrik yüklerini kullanabilen güçlü bir yaratıktır.',
      'zapwing': 'Yüksek hızlı uçuş yeteneği ve elektrik yüklerini kullanma kabiliyeti sayesinde rakiplerine karşı üstünlük sağlar.',
      'joltur': 'Joltur, Monster dünyasında bulunan bir electrik tipi yaratıktır. Elektrik enerjisini kontrol edebilir ve yüksek voltajlı saldırılar yapabilir.',
      'joltrik': ' Elektrik enerjisini daha etkin bir şekilde kontrol edebilir ve yüksek voltajlı saldırılarının yanı sıra elektrik yüklerini savunma amaçlı da kullanabilir.',
      'mysticon': 'Zihinsel güçlerini kullanarak düşmanlarına saldırabilir ve savunabilir. Aynı zamanda, zekası ve zihinsel yetenekleri sayesinde birçok problemi çözebilir.',
      'psypup': 'Zihinsel güçlerini kullanarak düşmanlarının zayıf noktalarını keşfedebilir ve çimen elementlerini kontrol edebilir. Ayrıca, sevimli görünümü ve oyuncu kişiliği ile sahibine eğlenceli anlar yaşatabilir.',
      'psydog': 'Zihinsel güçlerini daha etkin bir şekilde kullanabilir ve çimen elementlerini daha kapsamlı bir şekilde kontrol edebilir.',
      'dolphineon': 'Zeki ve meraklı bir karaktere sahip olmasıyla bilinir ve suda yaptığı hareketlerle etkileyici bir görünüme sahiptir.',
      'rockslide': 'Kuvvetli kas yapısı ve sağlam bir bedeni vardır. Yere çarparak yarattığı şok dalgalarıyla rakiplerini sarsar ve taş elementlerini kontrol edebilir. Güçlü ve kararlı bir kişiliği vardır.',
      'rockfist': 'Devasa kuvveti sayesinde zemini sarsabilir ve rakiplerine yıkıcı darbeler verebilir. Taş elementlerini daha etkin bir şekilde kullanabilir ve savunma mekanizmaları da çok gelişmiştir.',
      'silentpaw': 'Rakiplerini sessizce yaklaşıp saldırabilir ve hızlı hareketleri sayesinde kaçışları da oldukça kolaydır. Zeki ve uyanık bir karaktere sahiptir ve sahibine sadık bir arkadaşlık sunar.',
      'shadowclaw': 'Rakiplerini sessizce yaklaşarak saldırabilir. Kuvvetli pençeleri ve keskin dişleri sayesinde güçlü darbeler verebilir ve düşmanlarını kolayca alt edebilir. İnatçı ve cesur bir kişiliği vardır.',
      'electromon': "Electrik tipi bir Monster'dır. Elektrik yükü taşıyarak düşmanlarına hasar verebilir ve hızlı bir şekilde hareket edebilir.",
      'eaglestorm': "Flying tipi bir Monster'dır. Güçlü kanatları sayesinde hızlı bir şekilde uçabilir ve yüksek yerlerden düşmanlarına saldırabilir.",
      'skywing': "Flying tipi bir Monster'dır. Saldırılarında keskin pençelerini kullanır ve güçlü kanatları sayesinde yüksek hızlarda uçabilir.",
      'woolie': "Electric tipi bir Monster'dır. Yumuşak yünleri yüksek voltajlı elektrik yükleri taşır ve düşmanlarına saldırır.",
      'wooliec': "Woolie'nin bir üst evrimidir. Daha güçlü bir elektrik yükü taşır ve yünleri daha kalın ve daha dirençlidir.",
      'wooliectra': " Wooliec'in bir üst evrimidir. Yüksek voltajlı elektrik yükleri taşır ve yünleri yıldırım şeklinde parlar. Savunma ve saldırıda daha yeteneklidir.",
      'spookums': "Ghost tipi bir Monster'dır. Sevimli şekilde görünen bir hayalet formuna sahiptir. Düşmanlarını ürkütmek ve rahatsız etmek için farklı hileler kullanır.",
      'spookram': "Spookums'un bir üst evrimidir. Daha güçlü bir hayalet formu alır ve düşmanlarını daha etkili bir şekilde korkutabilir. Ayrıca güçlü Ghost tipi saldırılarına sahiptir.",
      'nimowl': "Psişik tipi bir Monster'dır ve bir baykuşa benzer. Zeki ve hızlıdır ve düşmanlarını kafa karıştırıcı psişik saldırılarla alt edebilir.",
      'wisowl': "Nimowl'un bir üst evrimidir.Daha keskin bir görüşü vardır ve gece avı yapmak için idealdir. Wisowl, düşmanlarını zihinsel olarak manipüle edebilen daha güçlü psişik saldırılara sahiptir.",
      'fliefox': "Fliefox, Monster dünyasında tilkiye benzeyen bir Normal tipidir. Çok hızlı koşabilir ve zıplayabilir. Sinsi bir doğası vardır ve düşmanlarına şaşırtıcı saldırılar yapabilir.",
      'fluffox': "Fluffox, Monster dünyasında Fliefox'un bir üst evrimidir. Daha kurnaz ve güçlüdür. Kürkü, havada uçarken de ona koruma sağlar ve keskin pençeleri rakiplerine zarar verebilir.",
      'drogie': 'Buz elementi taşıyan, ejderha benzeri bir canavardır. Gökyüzünde uçabilir ve ölümcül buz çıkışları yapabilir.',
      'drogice': 'Daha da güçlü bir buz ejderhasına dönüşür. Daha güçlü buz saldırıları yapabilir ve daha hızlı hareket edebilir. ',
      'drogrost': 'Buzun yanı sıra suyu da kontrol edebilir. Çok daha büyük ve güçlüdür ve diğer canavarlara karşı ezici bir üstünlük sağlar.',
      'monrass': 'Maymuna benzer çimen tipi Monster. Sarmaşıklarla arası çok iyidir.',
      'gorrass': "Monrass'ın bir üst evrimidir. Sarmaşıklarla ve yapraklarla kaplı vücudu bir gorile benzer.",
      'flamerock': 'Bu karınca benzeri ateş tipi Monster çok hızlı hareket eder. Ve ateş saldırılar çok can acıtıcı olabilir.',
      'flameburst': "Flamerock'un bir üst evrimidir. Evrimle gelen kafalarla birlikte ateş ısırığı saldırısıyla düşmanına ölümcül darbeler verir.",
      'vaseblade': 'Tohumundan çıktığı günden beri çimeni kontrol etme yeteneğine sahiptir. Fakat hala saksıya mahkumdur.',
      'leafblade': "Vaseblade'in bir üst evrimidir. Artık kökleri güçlenmiş ve saksıdan ayrılmıştır. Bununla birlikte çimen tipi saldırıları daha hızlanmıştır.",
      'forestblade': "Leafblade'in bir üst evrimidir. Bu evrimle birlikte ormana seslenme yeteğini açılır ve ormandaki sarmaşık ve yaprakları kullanabilir.",
      'glimmer': 'Buzların minik perisi olarak bilinir. Çok hızlı kanat çırparak buz hortumu oluşturabilir.',
      'schimmer': "Glimmer'in bir üst evrimidir. Bu evrimle eski hızı bir miktar düşmüş olsa da buz saldırıları epey güçlenmiştir.",
      'dunebelle': 'Çölün yalnız perisidir. Kanat çırpışlarıyla kum fırtınası yaratabilir ve düşman saldırılarından kaçabilir.',
      'infernus': 'Ateş tipi bir peridir. Yüksek ateş gücüne sahiptir ve ateşin kontrolü konusunda uzmandır.',
      'blazenus': "Infernus'un bir üst evrimidir. Daha da güçlü ateş özelliklerine sahiptir ve daha büyük bir kanat açıklığına sahiptir, bu da daha hızlı uçmasına olanak tanır.",
      'whispurr': "Görünüşüyle kedilere benzeyen, hızlı hareket eden ve hayalet güçlerine sahip bir 'Ghost' tipi yaratıktır.",
      'ghosteroid': 'Daha güçlü hayalet güçlerine sahip bir evrimdir ve diğer yaratıkların enerjilerini emerek güçlenebilir.',
      'toxibug': 'Monster evrenindeki en güçlü böcektir. Çok hızlı uçamaz fakat saldırıları epey etkilidir.',
      'toxiban': "Toxibug'un bir üst evrimidir. Gelişmiş kanatlarıyla çok hızlı uçabilir. O kusmuk saldırısını yaptığında etrafında olmak istemezsiniz.",
      'citrusclaw': "Turuncu bir vahşi kediye benzeyen bu Monster hızlı pati vuruşlarıyla düşmanlarına saldırır. Düşman saldırılarından kaçmakta da uzmandır.",
      'gingerpaw': "Citrusclaw'ın bir üst evrimi. Bu evrimle hızına hız katmıştır ve pati darbeleri güçlenmiştir. Ve artık saklanma konusunda da uzmandır.",
      'poliba': 'İstediği zaman kafasının üstündeki keseyi patlatarak içindeki zehriyle düşmanlarına saldırır. Yenilenme özelliği ile çok kısa bir sürede kesesini yeniler',
      'skov': 'Çiçekleri ve yaprakları kontrol etme gücü sayesinde düşmanlarına saldırı yapabilir ve ya kendini koruyabilir. Kendini korumak gerekmediği sürece zararsızdır.',
      'skovie': "Skov'un bir üst evrimi. Yaprak ve çiçek kontrol yeteneği çok gelişmiştir. Düşmanlarına saldırı için bir çiçeği bile tohumundan çıkarabilir.",
      'rhinohorn': "Çelikten bile sert derisi vardır. Bu sayede savunma yeteneği oldukça gelişmiştir. Bedeninin ağırlığına rağmen çok da hızlıdır.",
      'rhinorock': "Rhinohorn'un bir üst evrimidir. Bu evrimle boynuz saldırı hasarı çokça artmıştır.",
      'seebreeze': 'Genellikle denizlerde veya plajlarda görülür. Çok insan canlısıdır. Avlanırken su altında çok hızlı hareket edebilir.',
      'seastorm': "Seebreeze'nin bir üst evrimidir. Zırhı kalınlaşmış ama bununla birlikte de güzelleşmiştir. Rakiplerini su girdabı oluşturarak alt eder.",
      'flamie': 'Kanatları sayesinde havada hızlıca hareket edebilir ve düşmanlarının üzerine ateş topları fırlatabilir.',
      'flabie': 'Ateşe karşı yüksek dayanıklılığa sahiptir ve düşmanlarının ateş bazlı saldırılarına karşı oldukça dirençlidir.',
      'feliphys': "Antik çağlardan beri yaşadığı düşünülen bir Monster'dır. Sevimli göründüğü kadar da güçlüdür. Psişik güçleriyle her şeyi kontrol edebilir.",
      'mindlion': "Feliphys'in bir üst evrimidir. Düşmanlarının zekasını kontrol ederek saf dışı bırakmayı çok sever. Doğal bir liderdir.",
      'dracotide': 'Ejderhalar diyarının sevimli bir üyesidir. Çok hızlı uçabilir ve bununla birlikte suyu da ustaca kontrol edebilir.',
      'dracoflow': "Gövdesinin büyüklüğü sebebiyle korkutucu dursa da çok sevimli bir Monster'dır. Kuyruk darbeleriyle gücüne güç katmıştır.",
      'frostbite': 'Soğuklara karşı çok dirençlidir ve soğuğu kendi lehine kullanabilir. Onun güçlü çenesinden kaçmalısınız.',
      'frostitoes': "Frostbite'in bir üst evrimidir. Soğuk direnci daha da artmış ve pençeleri epey güçlenmiştir. Çok yükseklerden uçabilir.",
      'minei': "Madenci ve sevimli bir Monster'dır. Yeri hızlıca kazıp saklanabilir ve ya saldırabilir.",
      'minerax': "Minei'nin bir üst evrimidir. Artık yeri çok daha hızlı kazıp yerin içinde çok daha hızlı hareket edebilir.",
      'fluffernut': 'Fluffetnut, zehirli tozlarla dolu çimenlerden oluşan bir alan yaratarak düşmanlarını zehirleyebilir. Ayrıca, düşmanlarının saldırılarına karşı yüksek dayanıklılığa sahiptir.',
      'razorleaf': 'Keskin bıçak gibi olan yaprakları sayesinde düşmanlarını kolayca kesip parçalayabilir. Ayrıca zehir tozu saldırısı epey güçlenmiştir.',
      'spork': "Monster evreninin en sevimli üyesi olabilir. Elektriği kontrol etme yeteneğini henüz çok iyi kullanamıyor.",
      'sporkle': "Spork'un bir üst evrimidir. Elektriği kontrol etmeyi artık öğrenmiş ve bununla birlikte düşmanlarını alt etmek için bir kaç saldırı üretmiştir.",
      'zazzle': "Sporkle'nin bir üst evrimidir. Uzayan kuyruğu sayesinde elektrik akımlarınla kuyruğunla yön verebilir.",
      'chiliwrath': "Doğal bir lider olan bu Monster ateş kontrol etme yeteneği sayesinde gücüne güç katmıştır.",
      'chiliclaw': 'Daha güçlü pençe darbeleri ve daha sıcak ateş sebebiyle yenilmesi çok güçtür. Onunla savaşmak pek akıllıca değil',
      'doldog': 'Çok hızlı koşabilir ve buz kontrol etme yeteneğiyle düşmanlarına saldırabilir. ',
      'roseburst': 'Yüksek hızlı hareketleri sayesinde düşmanlarının saldırılarından kaçabilir ve uzaktan bitki spreyi kullanarak düşmanlarını zehirleyebilir. ',
      'flowerburst': 'Ormanda çok iyi kamufle olabilir. Sinsi bir şekilde düşmanına yaklaşır ve onu isterse zehirleyebilir.',
      'frostie': "Çok sevimli gözüken ama tehlikeli bir Monster'dır. Güçlü vücut darbeleri verebilir.",
      'froster': "Frostie'nin bir üst evrimidir. Vücut darbeleri gelişmiş ve bununla birlikte buz kontrolü yeteneğiyle gücüne güç katmıştır. ",
      'dolie': 'Çok hızlı bir şekilde yüzebilir ve su girdaplarıyla düşmanlarına saldırabilir.',
      'dolphie': 'Çok insan canlısıdır ve insanlarla yüzmeyi çok sever. Düşmanlarını su darbeleriyle alt edebilir.',
      'fenr': 'Ejderhalar diyarının sevimli bir üyesidir. Çok hızlı uçabilir ve zehir saldırısı yapabilir.',
      'fenrago': 'Vücudu epey büyümüş kanatları uzamıştır. Bu sayede çok hızlı uçabilir. Vücudundaki zehir de güçlenmiştir. Bu sayede düşmanlarını alt edebilir.',
      'mindwave': "Psişik saldırı yapabilen robot Monster'dır. Kendine psişik saldırı yapıp uçmayı keşfettiği söylenmektedir.",
      'psywave': 'Psişik saldırılarda uzmanlaşmıştır. Ve zırhı çelikten de serttir. Onu alt etmek hiç de kolay değildir.',
      'boolder': 'Çok küçük ve çok hızlıdır. Toprağı çok iyi bir şekilde kazabilir. Altına saklanabilir veya kazdıklarınla düşmana saldırabilir.',
      'boolderback': "Boolder'ın bir üst evrimidir. Çok hızlı koşabilir. Ve kaya saldırılarında uzmandır.",
      'aquazoid': 'Su altında hızlıca hareket edebilir ve düşmanlarının saldırılarına karşı su kabarcıkları kullanarak kendini koruyabilir. Su altında uzun süre hayatta kalabilir.',
      'thunderstrike': "Bu Monster ayak bastığı her yere elektrik akımı bırabilir. Çok güçlü voltaj saldırıları yapar. Doğal bir liderdir. ",
      'bippitibop': "Düşmanlarıyla eğlenmeyi çok sever. Çok iyi bir sihirbaz ve aynı zamanda çok güçlü bir Monster'dır",
      'venomous': "Çok zehirli bir Monster'dır. Kuyruğunda yüksek dozda zehir vardır. Hızlı hareket edebilir.",
      'psycodactyl': 'Beyin gücünü kullanarak düşmanlarının zihinlerini okuyabilir ve onların zihinlerinde kargaşa yaratabilir. Ayrıca, yüksek hızlı uçuş yeteneği sayesinde düşmanlarının saldırılarından kaçabilir.',
      'contactus': 'BİZE ULAŞIN',
      'playagain': 'Yeniden oynamak ister misin?',
      'outofenergy': "Oyuna girecek enerjin yok!",
      'watchadsforenergy': '5 Energy için reklam izle',
    },
    'ar_AR': {
      'youneedtobuy': 'يجب عليك شراء هذا الوحش للحصول على هذه الصفحة',
      '1dollar': '~ 1\$',
      '5dollar': '~ 5\$',
      '10dollar': '~ 10\$',
      'loginhint': 'إذا لم يكن لديك حساب ، يمكنك المتابعة بالنقر فوق EASY REGISTER (تسجيل سهل). إذا كان لديك حساب ، فيمكنك متابعة تسجيل الدخول السهل.',
      'easylogin': 'EASY LOGIN',
      'easyregister': 'EASY REGISTER',
      'seeyousoon': 'قريباً',
      'hintcandy': "يمكنك شراء الوحوش من صفحة 'مجموعتي' مع الحلوى التي تم جمعها. يمكنك لعب الألعاب المصغرة لكسب الحلوى أو يمكنك الحصول عليها من السوق.",
      'hintenergy': 'يتم تحميل الطاقة إلى حسابك التلقائي كل 5 دقائق أو يمكنك شراء الطاقة من صفحة السوق.',
      'no': 'لا',
      'yes': 'نعم',
      'withdraw': ' =هل تريد الانسحاب? ',
      'error': 'خطأ',
      'mail': 'أدخل البريد...',
      'validMail': 'أدخل بريدا إلكترونيا صالحا...',
      'password': 'أدخل كلمة المرور الخاصة بك...',
      'passwordLength': 'يجب أن تتكون كلمة المرور الخاصة بك من 6 أحرف على الأقل...',
      'login': 'الدخول',
      'register': 'سجل',
      'profile': 'الملف الشخصي',
      'mycollection': 'مجموعتي',
      'email1': 'الرجاء استخدام بريد إلكتروني بسيط. john@example.com - john@gmail.com - john1@example.com',
      'signout': 'تسجيل الخروج',
      'shoppingpage': 'شراء الوحش',
      'monsterbuy': 'هل توافق على شراء الوحش?',
      'buy': 'صقيل آل',
      'cancel': 'استسلم',
      'watch2x': 'الإعلان عن 2x س',
      'succesfulbuy': 'كان الشراء ناجحا',
      'unsuccesfulbuy': 'فشل الشراء',
      'okay': 'واخا',
      'succesful': 'ناجح',
      'unsuccesful': 'غير ناجح',
      'selectfighter': 'اختر بطلك',
      'congratulations': 'مبروك',
      'solved': 'لقد نجحت في حل اللغز',
      'youwon': 'لقد فزت!',
      'watch': '1 إعلان عن الحلوى',
      'watchAds': 'شاهد الفيديو',
      'gameover': 'المسرحية انتهت',
      'youlost': 'لقد خسرت!',
      'isnotready': 'إنه غير مستعد لهذا',
      'verypowerful': 'قام بهجوم قوي جدا',
      'powerful': 'قام بهجوم قوي',
      'weak': 'قام بهجوم ضعيف',
      'health': 'الروح',
      'time': 'الوقت',
      'second': 'ثانيا',
      'cardgame': 'مطابقة البطاقة',
      'hold': 'اضغط مع الاستمرار',
      'repeat': 'مجددا',
      'lookmines': 'انظر إلى المناجم',
      'presswhenyouwon': 'انقر عند الفوز',
      'poketype': 'نوع الوحش',
      'weakness': 'نقاط الضعف',
      'power': 'السلطة',
      'speed': 'السرعة',
      'evolve': 'التطور',
      'health2': 'الروح',
      'move': 'تحرك',
      'chooseimage': 'اختر صورة',
      'exitgame': ':اخرج من اللعبة للحصول على الحلوى التي فزت بها',
      'alreadybuyed': "لديك بالفعل هذا الوحش.",
      'start': 'ابدأ',
      'pause': 'توقف',
      'left': 'اليسار',
      'right': 'صحيح',
      'boost': 'تسريع',
      'rotate': 'تدوير',
      'resume': 'تابع',
      'pausegame': 'توقفت اللعبة',
      'adsfor': 'مشاهدة الإعلانات',
      'next': 'التالي',
      'end': 'إنهاء',
      'confirmcard': 'عند الفوز في المباراة ، وتكسب 1 الحلوى. يمكنك الاستمرار في اللعبة لمدة 1 الطاقة.',
      'confirmmine': 'عند الفوز في المباراة ، وتكسب 5 الحلوى. يمكنك الاستمرار في اللعبة لمدة 1 الطاقة.',
      'back': 'العودة',
      'letsgo': "ابدأ",
      'skate': 'تكسب 1 الحلوى لكل 20 نقطة. يمكنك الاستمرار لمدة 2 الطاقة.',
      'monsterfly': 'يمكنك الحصول على 1 الحلوى لكل 10 نقطة. يمكنك الاستمرار لمدة 2 الطاقة.',
      'monstertetris': 'تحصل على 1 حلوى لكل 1000 نقطة. يمكنك الاستمرار لمدة 2 الطاقة.',
      'puzzlesize': 'اختيار حجم اللغز',
      'choosepuzzlesize': 'حجم اللغز',
      'games': 'ألعاب',
      'backtomainmenu': 'العودة إلى القائمة الرئيسية',
      'florass': 'فلوراس هو مخلوق العشب في العالم الوحش. يتغذى على الأوراق وله أشواك سامة. يمكن استخدامه في الدفاع والهجوم ، فهو يفيد المالك.',
      'sparkie': 'هناك نار أبدية في جسمك تحترق حتى تموت. يتقيأ حمى ساخنة في هجماته . إنه زعيم طبيعي وصياد محترم.',
      'sparken': 'هجومه الأكثر شهرة هو خرطوم الحريق. أصبح قويا جدا بفضل خرطوم الحريق الذي رشه من فكه القوي جدا.',
      'aquadra': 'أكوادرا هو مخلوق من نوع المياه التي يمكن السيطرة على عناصر المياه في العالم الوحش. هو الأمثل جسده للمياه ولديه القدرة على السباحة بسرعة.',
      'shockwing': 'شوكوينغ هو مخلوق نوع الطيران والكهربائية وجدت في العالم الوحش. إنه مخلوق قوي يمكنه الطيران بسرعة عالية واستخدام الشحنات الكهربائية.',
      'zapwing': 'لديها ميزة على منافسيها بفضل قدرتها على الطيران عالية السرعة والقدرة على استخدام الشحنات الكهربائية.',
      'joltur': 'جولتور هو مخلوق من النوع الكهربائي موجود في عالم الوحوش. يمكنه التحكم في الطاقة الكهربائية وتنفيذ هجمات الجهد العالي.',
      'joltrik': ' يمكنه التحكم في الطاقة الكهربائية بشكل أكثر فعالية واستخدام الشحنات الكهربائية لأغراض دفاعية ، بالإضافة إلى هجمات الجهد العالي.',
      'mysticon': 'يمكنه مهاجمة أعدائه والدفاع عنهم باستخدام قواه العقلية. في الوقت نفسه ، بفضل ذكائه وقدراته العقلية ، يمكنه حل العديد من المشكلات.',
      'psypup': 'باستخدام قواه العقلية ، يمكنه اكتشاف نقاط ضعف أعدائه والتحكم في عناصر العشب. بالإضافة إلى ذلك ، مع مظهره اللطيف وشخصيته المرحة ، يمكن أن يمنح صاحبه لحظات ممتعة.',
      'psydog': 'يمكنه استخدام قواه العقلية بشكل أكثر فعالية والتحكم في عناصر العشب بشكل أكثر شمولا.',
      'dolphineon': 'وهو معروف بامتلاكه شخصية ذكية وفضولية وله مظهر مثير للإعجاب مع تحركاته في الماء.',
      'rockslide': 'لديه بنية عضلية قوية وجسم صلب. 1 نوفمبر 2016. يهز خصومه بموجات الصدمة التي يخلقها عن طريق ضرب الأرض ويمكنه التحكم في العناصر الحجرية. لديه شخصية قوية وحازمة.',
      'rockfist': 'بفضل قوتها الهائلة ، يمكنها أن تهز الأرض وتوجه ضربات مدمرة لخصومها. يمكنها استخدام العناصر الحجرية بشكل أكثر فعالية ، كما تحسنت آليات دفاعها كثيرا.',
      'silentpaw': 'وقال انه يمكن الاقتراب بهدوء ومهاجمة خصومه ، وبفضل تحركاته السريعة ، هروبهم هو أيضا من السهل جدا. لديها شخصية ذكية وتنبيه وتقدم صداقة مخلصة لمالكها.',
      'shadowclaw': 'يمكنه مهاجمة خصومه من خلال الاقتراب منهم بهدوء. بفضل مخالبها القوية وأسنانها الحادة ، يمكنها توجيه ضربات قوية وهزيمة أعدائها بسهولة. لديه شخصية عنيدة وشجاعة.',
      'electromon': "إنه وحش من النوع الكهربائي. من خلال حمل شحنة كهربائية ، يمكنه إتلاف أعدائه والتحرك بسرعة.",
      'eaglestorm': "إنه وحش من النوع الطائر. بفضل أجنحتها القوية ، يمكنها الطيران بسرعة ومهاجمة أعدائها من الأماكن المرتفعة.",
      'skywing': "إنه وحش من النوع الطائر. يستخدم مخالب حادة في هجماته ويمكنه الطيران بسرعات عالية بفضل أجنحته القوية.",
      'woolie': "إنه وحش من النوع الكهربائي. يحمل صوفهم الناعم شحنات كهربائية عالية الجهد ويهاجم أعدائهم.",
      'wooliec': "إنه تطور كبير من وولي. يحمل شحنة كهربائية أقوى ، وصوفه أكثر سمكا وأكثر مقاومة.",
      'wooliectra': " بل هو تطور أعلى من ووليك. يحمل شحنات كهربائية عالية الجهد ، ويضيء صوفه على شكل برق. هو أكثر موهبة في الدفاع والهجوم.",
      'spookums': "إنه وحش من نوع الأشباح. لديه شكل شبح يبدو لطيفا. انه يستخدم الحيل المختلفة لتخويف وإزعاج أعدائه.",
      'spookram': "بل هو تطور السوبر من سبوكوم. يأخذ شكل شبح أكثر قوة وقادر على تخويف أعدائه بشكل أكثر فعالية. كما أن لديها هجمات قوية من نوع الأشباح.",
      'nimowl': "النوع النفسي هو وحش ويشبه البومة. إنه ذكي وسريع ويمكنه هزيمة أعدائه بهجمات نفسية مربكة.",
      'wisowl': "إنه تطور فائق لـ Nimowl.It لديه رؤية أكثر وضوحا ومثالية للصيد الليلي. ويسول لديها هجمات نفسية أكثر قوة التي يمكن التلاعب عقليا أعدائهم.",
      'fliefox': "فليفوكس هو نوع عادي يشبه الثعلب في عالم الوحوش. يمكنه الركض والقفز بسرعة كبيرة. لديه طبيعة متستر ويمكن أن تجعل هجمات مفاجئة على أعدائه.",
      'fluffox': "فلوفوكس هو تطور سوبر فليفوكس في العالم الوحش. هو أكثر دهاء وقوة. كما يوفر فروها الحماية عند الطيران في الهواء ، ويمكن أن تلحق مخالبها الحادة الضرر بالخصوم.",
      'drogie': 'إنه وحش يشبه التنين يحمل عنصر الجليد. يمكن أن تطير في السماء وجعل مخارج الجليد القاتلة.',
      'drogice': 'يتحول إلى تنين جليدي أكثر قوة. يمكنه القيام بهجمات جليدية أقوى والتحرك بشكل أسرع. ',
      'drogrost': 'يمكنه التحكم في الماء وكذلك الجليد. إنه أكبر وأقوى بكثير وله تفوق ساحق على الوحوش الأخرى.',
      'monrass': 'وحش من نوع العشب يشبه القرد. انه جيد جدا مع فاينز. ديسمبر.',
      'gorrass': "إنه تطور كبير من مونراس. جسمها ، المغطى بالكروم والأوراق ، يشبه الغوريلا.",
      'flamerock': 'هذا الوحش نوع النار مثل النمل يتحرك بسرعة كبيرة. ويمكن أن تكون نوبات الحمى مؤلمة للغاية.',
      'flameburst': "بل هو تطور السوبر من فلاميروك. جنبا إلى جنب مع الرؤوس التي تأتي مع التطور ، وقال انه يتعامل ضربات قاتلة لعدوه مع هجوم لدغة النار.",
      'vaseblade': 'لديه القدرة على التحكم في العشب منذ اليوم الذي خرج فيه من البذرة. لكنها لا تزال محكوم عليها بالوعاء.',
      'leafblade': "بل هو تطور أعلى من فاسيبلاد. الآن يتم تقوية الجذور وفصلها عن الوعاء. ومع ذلك ، تسارعت الهجمات من نوع العشب أكثر.",
      'forestblade': "بل هو تطور أعلى من ليفبليد. مع هذا التطور ، تفتح القدرة على الاتصال بالغابة ويمكنه استخدام الكروم والأوراق في الغابة.",
      'glimmer': 'وهي معروفة باسم جنية الجليد الصغيرة. يمكنه إنشاء خرطوم ثلج عن طريق رفرفة جناحيه بسرعة كبيرة.',
      'schimmer': "وهو تطور كبير من بصيص. على الرغم من أن سرعته السابقة قد انخفضت قليلا مع هذا التطور ، إلا أن هجمات الجليد أصبحت قوية جدا.",
      'dunebelle': 'هي جنية الصحراء الوحيدة. يمكنه خلق عواصف رملية بلوحات جناحه والهروب من هجمات العدو.',
      'infernus': 'إنها جنية من نوع النار. لديه قوة نيران عالية وخبير في السيطرة على النار.',
      'blazenus': "إنه تطور فائق للجحيم. لديها خصائص حريق أكثر قوة ولها جناحيها أكبر ، مما يسمح لها بالطيران بشكل أسرع.",
      'whispurr': "إنه مخلوق من النوع الشبح يشبه القطط في المظهر ، ويتحرك بسرعة ولديه قوى شبح.",
      'ghosteroid': 'إنه تطور مع قوى أشباح أقوى ويمكن تقويته عن طريق امتصاص طاقات المخلوقات الأخرى.',
      'toxibug': 'إنها أقوى حشرة في عالم الوحوش. لا يستطيع الطيران بسرعة كبيرة ، لكن هجماته فعالة للغاية.',
      'toxiban': "بل هو تطور السوبر من توكسيبوج. يمكن أن تطير بسرعة كبيرة مع أجنحتها المتقدمة. أنت لا تريد أن تكون حوله عندما يفعل ذلك هجوم التقيؤ.",
      'citrusclaw': "يشبه القط الوحشي البرتقالي ، يهاجم هذا الوحش أعدائه بضربات مخلب سريعة. وهو أيضا خبير في الهروب من هجمات العدو.",
      'gingerpaw': "تطور كبير من الحمضيات. مع هذا التطور ، أضاف السرعة إلى سرعته وأصبحت نبضات مخلبه أقوى. والآن هو خبير في الاختباء أيضا.",
      'poliba': 'عندما يريد ، ينفجر الحقيبة على رأس رأسه ويهاجم أعدائه بالسم في الداخل. يجدد الحقيبة في وقت قصير جدا مع ميزة التجديد',
      'skov': 'بفضل قوة السيطرة على الزهور والأوراق ، يمكنه مهاجمة أعدائه وحماية نفسه. إنه غير ضار طالما أنه ليس من الضروري حماية نفسه.',
      'skovie': "تطور فائق من سكوف. تم تطوير القدرة على التحكم في الأوراق والزهور بشكل كبير. يمكنه حتى استخراج زهرة من بذورها لمهاجمة أعدائه.",
      'rhinohorn': "لها جلد أصعب من الفولاذ. بفضل هذا ، تحسنت القدرة الدفاعية كثيرا. على الرغم من وزن جسده ، فهو سريع جدا.",
      'rhinorock': "إنه تطور فائق لرينوهورن. مع هذا التطور ، زاد ضرر هجوم القرن كثيرا.",
      'seebreeze': 'عادة ما يرى في البحار أو على الشواطئ. إنه بشري للغاية-على قيد الحياة. يمكن أن تتحرك بسرعة كبيرة تحت الماء عند الصيد.',
      'seastorm': "إنه تطور فائق من سيبريز. وقد سميكة درعه ، ولكن مع ذلك أصبح أيضا جميلة. انه يهزم خصومه من خلال خلق دوامة المياه.",
      'flamie': 'بفضل جناحيه ، يمكنه التحرك بسرعة في الهواء ورمي الكرات النارية على أعدائه.',
      'flabie': 'لديها مقاومة عالية لاطلاق النار ومقاومة للغاية للهجمات القائمة على النار من أعدائها.',
      'feliphys': "إنه وحش يعتقد أنه عاش منذ العصور القديمة. لطيف قوي كما يبدو. يمكنه التحكم في كل شيء بقواه النفسية.",
      'mindlion': "إنه تطور فائق لفيليفيس. يحب القضاء على ذكاء أعدائه من خلال السيطرة عليهم. إنه قائد طبيعي.",
      'dracotide': 'إنه عضو لطيف في أرض التنانين. يمكن أن تطير بسرعة كبيرة ، ومعها ، يمكنها أيضا التحكم بمهارة في الماء.',
      'dracoflow': "على الرغم من أنها تبدو مخيفة بسبب حجم جسمها ، إلا أنها وحش لطيف للغاية. أضاف قوة إلى قوته بضربات الذيل.",
      'frostbite': 'إنه مقاوم جدا للبرد ويمكنه استخدام البرد لصالحه. يجب عليك الهروب من فكه القوي.',
      'frostitoes': "إنه تطور كبير لقضمة الصقيع. زادت مقاومته الباردة أكثر وأصبحت مخالبه قوية جدا. يمكنه الطيران عاليا جدا.",
      'minei': "وهو عامل منجم وحش لطيف. يمكنه حفر الأرض بسرعة أو الاختباء أو الهجوم.",
      'minerax': "إنه تطور فائق لميني. الآن يمكنه حفر الأرض بشكل أسرع والتحرك بشكل أسرع داخل الأرض.",
      'fluffernut': 'يمكن للفلوفيتنوت أن يسمم أعدائه عن طريق إنشاء منطقة من العشب مليئة بالمساحيق السامة. بالإضافة إلى ذلك ، لديها مقاومة عالية لهجمات أعدائها.',
      'razorleaf': 'بفضل أوراقها ، التي تشبه السكاكين الحادة ، يمكنها بسهولة قطع أعدائها وتحطيمهم. بالإضافة إلى ذلك ، أصبح هجوم مسحوق السم قويا جدا.',
      'spork': "قد يكون العضو الأكثر روعة في عالم الوحش. إنه غير قادر بعد على استخدام قدرته على التحكم في الكهرباء بشكل جيد للغاية.",
      'sporkle': "بل هو تطور أعلى من سبورك. لقد تعلم الآن التحكم في الكهرباء وأنتج أيضا عدة هجمات لهزيمة أعدائه.",
      'zazzle': "إنه تطور كبير من سبوركل. بفضل ذيله الممدود ، يمكنه توجيه التيارات الكهربائية بذيلك.",
      'chiliwrath': "قائد طبيعي ، أضاف هذا الوحش قوة إلى قوته بفضل قدرته على السيطرة على النار.",
      'chiliclaw': 'من الصعب جدا الهزيمة بسبب ضربات المخلب الأقوى والنار الأكثر سخونة. انها ليست ذكية جدا لمحاربته',
      'doldog': 'يمكنه الركض بسرعة كبيرة ومهاجمة أعدائه بقدرته على التحكم في الجليد. ',
      'roseburst': 'بفضل تحركاته عالية السرعة ، يمكنه الهروب من هجمات أعدائه وتسميم أعدائه باستخدام رذاذ النبات من بعيد. ',
      'flowerburst': 'يمكن أن تكون مموهة جيدا في الغابة. يقترب خلسة من عدوه ويمكن أن يسممه إذا أراد.',
      'frostie': "إنه وحش لطيف المظهر ولكنه خطير. يمكنه توجيه ضربات قوية للجسم.",
      'froster': "إنه تطور كبير من فروستي. تحسنت ضربات جسده ومع هذا ، أضاف قوة إلى قوته من خلال قدرته على التحكم في الجليد. ",
      'dolie': 'يمكنه السباحة بسرعة كبيرة ومهاجمة أعدائه بدوامات الماء.',
      'dolphie': 'إنه مخلوق بشري للغاية ويحب السباحة مع الناس كثيرا. يمكنه هزيمة أعدائه بضربات المياه.',
      'fenr': 'إنه عضو لطيف في أرض التنانين. يمكن أن تطير بسرعة كبيرة ويمكن أن تجعل هجوم السم.',
      'fenrago': 'جسمه كبير جدا ، وأجنحته ممدودة. بفضل هذا ، يمكن أن تطير بسرعة كبيرة. كما أصبح السم في جسده أقوى. بهذه الطريقة ، يمكنه هزيمة أعدائه.',
      'mindwave': "الروبوت الذي يمكنه القيام بهجمات نفسية هو الوحش. يقال أنه قام بهجوم نفسي على نفسه واكتشف كيف يطير.",
      'psywave': 'وهو متخصص في الهجمات النفسية. ودرعه أصعب من الفولاذ. ليس من السهل إلحاق الهزيمة به على الإطلاق.',
      'boolder': 'انها صغيرة جدا وسريعة جدا. يمكنه حفر التربة جيدا. يمكنك إخفاء تحته أو مهاجمة العدو مع الحفريات الخاصة بك.',
      'boolderback': "بل هو تطور السوبر من بوولدر. يمكنه الركض بسرعة كبيرة. وهو خبير في هجمات الصخور.",
      'aquazoid': 'يمكنه التحرك بسرعة تحت الماء وحماية نفسه من هجمات أعدائه باستخدام فقاعات الماء. يمكن أن يعيش تحت الماء لفترة طويلة.',
      'thunderstrike': "يمكن لهذا الوحش إرسال تيار كهربائي أينما تطأ قدمه. يجعل هجمات الجهد قوية جدا. إنه قائد طبيعي. ",
      'bippitibop': "يحب أن يكون متعة مع أعدائه. إنه ساحر جيد جدا وفي نفس الوقت وحش قوي جدا",
      'venomous': "إنه وحش سام للغاية. لديه جرعة عالية من السم في ذيله. يمكنه التحرك بسرعة.",
      'psycodactyl': 'باستخدام قوة دماغه ، يمكنه قراءة عقول أعدائه وخلق الفوضى في أذهانهم. بالإضافة إلى ذلك ، بفضل قدرته على الطيران عالية السرعة ، يمكنه الهروب من هجمات أعدائه.',
      'contactus': 'اتصل بنا',
      'playagain': 'هل تريد أن تلعب مرة أخرى?',
      'outofenergy': "ليس لديك الطاقة للدخول في اللعبة!",
      'watchadsforenergy': 'مشاهدة الإعلانات لمدة 5 الطاقة',
      'failedbuy': 'فشل الشراء',
    },
  };
}